// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: Explicit Resource Management
// subtest: SuppressedError
var __ok = (function () {
        var err1 = new Error();
        var err2 = new Error();
        var err3 = new Error();
        try {
          using _1 = { [Symbol.dispose]() { throw err1 } },
                _2 = { [Symbol.dispose]() { throw err2 } };
          throw err3;
        } catch (e) {
          return (
            e instanceof SuppressedError
            && e.error === err1
            && e.suppressed instanceof SuppressedError
            && e.suppressed.error === err2
            && e.suppressed.suppressed === err3
          );
        }
      
})();
if (__ok !== true) { throw new Error("compat-table check failed: " + __ok); }
