// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: Map.prototype.upsert
// subtest: WeakMap.prototype.getOrInsertComputed
var __ok = (function () {const a = {}, b = {};
const defaultCreator = (key) => 2;
const map = new WeakMap([[a, 1]]);
if (map.getOrInsertComputed(a, defaultCreator) !== 1) return false;
if (map.getOrInsertComputed(b, defaultCreator) !== 2) return false;
return map.get(a) === 1 && map.get(b) === 2;
})();
if (!__ok) { throw new Error("compat-table check failed: " + __ok); }
