package regexpjs

// esBinaryProperties is the ECMAScript-permitted set of lone Unicode binary
// property names (`\p{Name}`), mapping each canonical name and alias to its
// canonical name. Properties outside this set (e.g. Go's Other_Math, Hyphen,
// Prepended_Concatenation_Mark) are NOT valid ES property escapes and must be a
// SyntaxError, even though Go's unicode.Properties happens to contain them.
var esBinaryProperties = map[string]string{
	"ASCII_Hex_Digit": "ASCII_Hex_Digit", "AHex": "ASCII_Hex_Digit",
	"Alphabetic": "Alphabetic", "Alpha": "Alphabetic",
	"Bidi_Control": "Bidi_Control", "Bidi_C": "Bidi_Control",
	"Bidi_Mirrored": "Bidi_Mirrored", "Bidi_M": "Bidi_Mirrored",
	"Case_Ignorable": "Case_Ignorable", "CI": "Case_Ignorable",
	"Cased":                   "Cased",
	"Changes_When_Casefolded": "Changes_When_Casefolded", "CWCF": "Changes_When_Casefolded",
	"Changes_When_Casemapped": "Changes_When_Casemapped", "CWCM": "Changes_When_Casemapped",
	"Changes_When_Lowercased": "Changes_When_Lowercased", "CWL": "Changes_When_Lowercased",
	"Changes_When_NFKC_Casefolded": "Changes_When_NFKC_Casefolded", "CWKCF": "Changes_When_NFKC_Casefolded",
	"Changes_When_Titlecased": "Changes_When_Titlecased", "CWT": "Changes_When_Titlecased",
	"Changes_When_Uppercased": "Changes_When_Uppercased", "CWU": "Changes_When_Uppercased",
	"Dash":                         "Dash",
	"Default_Ignorable_Code_Point": "Default_Ignorable_Code_Point", "DI": "Default_Ignorable_Code_Point",
	"Deprecated": "Deprecated", "Dep": "Deprecated",
	"Diacritic": "Diacritic", "Dia": "Diacritic",
	"Emoji":           "Emoji",
	"Emoji_Component": "Emoji_Component", "EComp": "Emoji_Component",
	"Emoji_Modifier": "Emoji_Modifier", "EMod": "Emoji_Modifier",
	"Emoji_Modifier_Base": "Emoji_Modifier_Base", "EBase": "Emoji_Modifier_Base",
	"Emoji_Presentation": "Emoji_Presentation", "EPres": "Emoji_Presentation",
	"Extended_Pictographic": "Extended_Pictographic", "ExtPict": "Extended_Pictographic",
	"Extender": "Extender", "Ext": "Extender",
	"Grapheme_Base": "Grapheme_Base", "Gr_Base": "Grapheme_Base",
	"Grapheme_Extend": "Grapheme_Extend", "Gr_Ext": "Grapheme_Extend",
	"Hex_Digit": "Hex_Digit", "Hex": "Hex_Digit",
	"IDS_Binary_Operator": "IDS_Binary_Operator", "IDSB": "IDS_Binary_Operator",
	"IDS_Trinary_Operator": "IDS_Trinary_Operator", "IDST": "IDS_Trinary_Operator",
	"ID_Continue": "ID_Continue", "IDC": "ID_Continue",
	"ID_Start": "ID_Start", "IDS": "ID_Start",
	"Ideographic": "Ideographic", "Ideo": "Ideographic",
	"Join_Control": "Join_Control", "Join_C": "Join_Control",
	"Logical_Order_Exception": "Logical_Order_Exception", "LOE": "Logical_Order_Exception",
	"Lowercase": "Lowercase", "Lower": "Lowercase",
	"Math":                    "Math",
	"Noncharacter_Code_Point": "Noncharacter_Code_Point", "NChar": "Noncharacter_Code_Point",
	"Pattern_Syntax": "Pattern_Syntax", "Pat_Syn": "Pattern_Syntax",
	"Pattern_White_Space": "Pattern_White_Space", "Pat_WS": "Pattern_White_Space",
	"Quotation_Mark": "Quotation_Mark", "QMark": "Quotation_Mark",
	"Radical":            "Radical",
	"Regional_Indicator": "Regional_Indicator", "RI": "Regional_Indicator",
	"Sentence_Terminal": "Sentence_Terminal", "STerm": "Sentence_Terminal",
	"Soft_Dotted": "Soft_Dotted", "SD": "Soft_Dotted",
	"Terminal_Punctuation": "Terminal_Punctuation", "Term": "Terminal_Punctuation",
	"Unified_Ideograph": "Unified_Ideograph", "UIdeo": "Unified_Ideograph",
	"Uppercase": "Uppercase", "Upper": "Uppercase",
	"Variation_Selector": "Variation_Selector", "VS": "Variation_Selector",
	"White_Space": "White_Space", "space": "White_Space",
	"XID_Continue": "XID_Continue", "XIDC": "XID_Continue",
	"XID_Start": "XID_Start", "XIDS": "XID_Start",
}
