// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: Array.prototype.includes
// subtest: Array.prototype.includes is generic
var __ok = (function () {var passed = 0;
return [].includes.call(
  {
    get "0"() {
      passed = NaN;
      return 'foo';
    },
    get "11"() {
      passed += 1;
      return 0;
    },
    get "19"() {
      passed += 1;
      return 'foo';
    },
    get "21"() {
      passed = NaN;
      return 'foo';
    },
    get length() {
      passed += 1;
      return 24;
    }
  },
  'foo',
  6
) === true && passed === 3;
})();
if (!__ok) { throw new Error("compat-table check failed: " + __ok); }
