// Command gencldr reads two CLDR supplemental files and generates
// internal/engine/intl_cldr_gen.go: the alias tables that turn a language tag
// into its canonical form, and the likely-subtags table that
// Intl.Locale.prototype.maximize and minimize are defined in terms of.
//
// Usage:
//
//	go run ./tools/gencldr -cldr <dir> -out internal/engine/intl_cldr_gen.go
//
// The <dir> must contain, from
// https://github.com/unicode-org/cldr/tree/release-<n>/common/supplemental:
//
//	supplementalMetadata.xml   likelySubtags.xml
//
// The generated file is committed; regenerate only when bumping CLDR version.
//
// The tables are emitted as newline-separated string constants rather than map
// literals. A map literal of 7,789 entries is built at package init by every
// program that links the engine, whether or not it ever formats anything; a
// constant is read-only data in the binary and the map is built on first use,
// which for most hosts is never.
package main

import (
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type aliasEntry struct {
	Type        string `xml:"type,attr"`
	Replacement string `xml:"replacement,attr"`
	Reason      string `xml:"reason,attr"`
}

type likelyEntry struct {
	From string `xml:"from,attr"`
	To   string `xml:"to,attr"`
}

type metadata struct {
	Alias struct {
		Language    []aliasEntry `xml:"languageAlias"`
		Script      []aliasEntry `xml:"scriptAlias"`
		Territory   []aliasEntry `xml:"territoryAlias"`
		Variant     []aliasEntry `xml:"variantAlias"`
		Subdivision []aliasEntry `xml:"subdivisionAlias"`
	} `xml:"metadata>alias"`
}

type likelyDoc struct {
	Subtags []likelyEntry `xml:"likelySubtags>likelySubtag"`
}

func main() {
	dir := flag.String("cldr", "", "directory holding the CLDR supplemental XML")
	out := flag.String("out", "", "path of the Go file to write")
	flag.Parse()
	if *dir == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: gencldr -cldr <dir> -out <file.go>")
		os.Exit(2)
	}

	var meta metadata
	read(filepath.Join(*dir, "supplementalMetadata.xml"), &meta)
	var likely likelyDoc
	read(filepath.Join(*dir, "likelySubtags.xml"), &likely)

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by tools/gencldr. DO NOT EDIT.

package engine

// CLDR alias and likely-subtags data, for canonicalising a language tag and
// for AddLikelySubtags/RemoveLikelySubtags. See tools/gencldr.
`)

	// Aliases whose type is not a unicode_language_id -- the BCP 47
	// grandfathered and extlang forms, "i-default" and "zh-cmn-Hans" and the
	// like -- are dropped. ECMA-402 validates against unicode_locale_id, under
	// which those tags are not structurally valid in the first place, so an
	// entry keyed on one could never match and would only be weight.
	langAliases := filterLanguage(meta.Alias.Language)
	emit(&b, "cldrLanguageAliasData",
		"language aliases: a unicode_language_id prefix and what replaces it.",
		langAliases)
	emit(&b, "cldrScriptAliasData", "script aliases.", simple(meta.Alias.Script))
	emit(&b, "cldrRegionAliasData",
		"region aliases. A replacement with several regions in it is resolved\n"+
			"// against the likely-subtags table at canonicalisation time, so the\n"+
			"// list is kept whole here.",
		simple(meta.Alias.Territory))
	emit(&b, "cldrVariantAliasData", "variant aliases.", simple(meta.Alias.Variant))

	// The -u- and -t- keyword values have their own aliases, one file per key
	// family under common/bcp47. Both spellings a deprecated value can have --
	// an `alias` attribute on the canonical type, and a `preferred` attribute
	// on the deprecated one -- end up as the same kind of entry here.
	kw := keywordAliases(filepath.Join(*dir, "bcp47"))
	for _, e := range meta.Alias.Subdivision {
		// A subdivision alias reaches the -u- extension through two keys, `sd`
		// (the subdivision itself) and `rg` (a region override spelled as one).
		// A subdivision that split has several replacements; UTS 35 takes the
		// first, and unlike a territory there is no likely-subtags tie-break.
		repl := strings.Fields(dash(e.Replacement))
		if len(repl) == 0 {
			continue
		}
		for _, key := range []string{"sd", "rg"} {
			kw = append(kw, [2]string{key + "/" + dash(e.Type), repl[0]})
		}
	}
	emit(&b, "cldrKeywordAliasData",
		"keyword value aliases, keyed \"<key>/<deprecated value>\".", kw)

	// The likely-subtags value is written as a script+region pair whenever the
	// language is unchanged, which it is for all but the und-* entries. That is
	// most of the table and about a third of its bytes.
	var likelyPairs [][2]string
	for _, e := range likely.Subtags {
		from, to := dash(e.From), dash(e.To)
		lang := from
		if i := strings.IndexByte(from, '-'); i >= 0 {
			lang = from[:i]
		}
		if v, ok := strings.CutPrefix(to, lang+"-"); ok {
			to = v
		}
		likelyPairs = append(likelyPairs, [2]string{from, to})
	}
	emit(&b, "cldrLikelyData",
		"likely subtags. The value is the full tag when the language changes and\n"+
			"// the script-region remainder when it does not, which is the common case.",
		likelyPairs)

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "gofmt:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gencldr: %d language, %d script, %d region, %d variant, %d likely\n",
		len(langAliases), len(meta.Alias.Script), len(meta.Alias.Territory),
		len(meta.Alias.Variant), len(likelyPairs))
}

func read(path string, into any) {
	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()
	if err := xml.NewDecoder(f).Decode(into); err != nil {
		fmt.Fprintln(os.Stderr, path+":", err)
		os.Exit(1)
	}
}

func dash(s string) string { return strings.ReplaceAll(s, "_", "-") }

func simple(in []aliasEntry) [][2]string {
	out := make([][2]string, 0, len(in))
	for _, e := range in {
		out = append(out, [2]string{dash(e.Type), dash(e.Replacement)})
	}
	return out
}

// filterLanguage keeps the aliases whose type could actually occur in a
// structurally valid unicode_locale_id: a language subtag, optionally followed
// by a script, a region, or a variant.
func filterLanguage(in []aliasEntry) [][2]string {
	out := make([][2]string, 0, len(in))
	for _, e := range in {
		parts := strings.Split(dash(e.Type), "-")
		if !isLanguageSubtag(parts[0]) {
			continue
		}
		ok := true
		for _, p := range parts[1:] {
			if !isScriptSubtag(p) && !isRegionSubtag(p) && !isVariantSubtag(p) {
				ok = false
				break
			}
		}
		if ok {
			out = append(out, [2]string{dash(e.Type), dash(e.Replacement)})
		}
	}
	return out
}

func alpha(s string) bool {
	for i := 0; i < len(s); i++ {
		c := s[i] | 0x20
		if c < 'a' || c > 'z' {
			return false
		}
	}
	return len(s) > 0
}

func digits(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return len(s) > 0
}

func alnum(s string) bool {
	for i := 0; i < len(s); i++ {
		c := s[i] | 0x20
		if (c < 'a' || c > 'z') && (s[i] < '0' || s[i] > '9') {
			return false
		}
	}
	return len(s) > 0
}

func isLanguageSubtag(s string) bool {
	return alpha(s) && (len(s) == 2 || len(s) == 3 || (len(s) >= 5 && len(s) <= 8))
}
func isScriptSubtag(s string) bool { return len(s) == 4 && alpha(s) }
func isRegionSubtag(s string) bool {
	return (len(s) == 2 && alpha(s)) || (len(s) == 3 && digits(s))
}
func isVariantSubtag(s string) bool {
	return (len(s) >= 5 && len(s) <= 8 && alnum(s)) || (len(s) == 4 && digits(s[:1]) && alnum(s))
}

// emit writes one table as a sorted, newline-separated constant. Sorting is by
// key so the generated file has a stable diff across CLDR releases: a bumped
// version should show what changed, not a reshuffle.
func emit(b *strings.Builder, name, doc string, pairs [][2]string) {
	sort.Slice(pairs, func(i, j int) bool { return pairs[i][0] < pairs[j][0] })
	fmt.Fprintf(b, "\n// %s = %s\nconst %s = \"\" +\n", name, doc, name)
	seen := map[string]bool{}
	for _, p := range pairs {
		if seen[p[0]] {
			continue
		}
		seen[p[0]] = true
		fmt.Fprintf(b, "\t%q +\n", p[0]+" "+p[1]+"\n")
	}
	fmt.Fprintf(b, "\t\"\"\n")
}

// keyDoc is one common/bcp47 file: a handful of keys, each with its types.
type keyDoc struct {
	Keys []struct {
		Name  string `xml:"name,attr"`
		Types []struct {
			Name       string `xml:"name,attr"`
			Alias      string `xml:"alias,attr"`
			Deprecated string `xml:"deprecated,attr"`
			Preferred  string `xml:"preferred,attr"`
		} `xml:"type"`
	} `xml:"keyword>key"`
}

// keywordAliases reads every file in the bcp47 directory and returns the
// deprecated spellings of each keyword value, keyed "<key>/<value>".
func keywordAliases(dir string) [][2]string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var out [][2]string
	for _, f := range entries {
		if filepath.Ext(f.Name()) != ".xml" {
			continue
		}
		var doc keyDoc
		read(filepath.Join(dir, f.Name()), &doc)
		for _, k := range doc.Keys {
			for _, t := range k.Types {
				if t.Deprecated == "true" {
					// A deprecated type also carries the alias it replaced,
					// which points the wrong way: "islamicc" is deprecated in
					// favour of "islamic-civil" and lists it as an alias too.
					// Only the preferred direction is a canonicalisation.
					if t.Preferred != "" {
						out = append(out, [2]string{k.Name + "/" + t.Name, t.Preferred})
					}
					continue
				}
				for _, a := range strings.Fields(t.Alias) {
					out = append(out, [2]string{k.Name + "/" + strings.ToLower(a), t.Name})
				}
			}
		}
	}
	return out
}
