// Command gencldr reads two CLDR supplemental files and generates
// internal/engine/intl_cldr_gen.go: the alias tables that turn a language tag
// into its canonical form, and the likely-subtags table that
// Intl.Locale.prototype.maximize and minimize are defined in terms of.
//
// Usage:
//
//	go run ./tools/gencldr -cldr <dir> -out internal/engine/intl_cldr_gen.go
//
// The <dir> must contain, from
// https://github.com/unicode-org/cldr/tree/release-<n>/common/supplemental:
//
//	supplementalMetadata.xml   likelySubtags.xml   supplementalData.xml
//
// The generated file is committed; regenerate only when bumping CLDR version.
//
// The tables are emitted as newline-separated string constants rather than map
// literals. A map literal of 7,789 entries is built at package init by every
// program that links the engine, whether or not it ever formats anything; a
// constant is read-only data in the binary and the map is built on first use,
// which for most hosts is never.
package main

import (
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type aliasEntry struct {
	Type        string `xml:"type,attr"`
	Replacement string `xml:"replacement,attr"`
	Reason      string `xml:"reason,attr"`
}

type likelyEntry struct {
	From string `xml:"from,attr"`
	To   string `xml:"to,attr"`
}

type metadata struct {
	Alias struct {
		Language    []aliasEntry `xml:"languageAlias"`
		Script      []aliasEntry `xml:"scriptAlias"`
		Territory   []aliasEntry `xml:"territoryAlias"`
		Variant     []aliasEntry `xml:"variantAlias"`
		Subdivision []aliasEntry `xml:"subdivisionAlias"`
	} `xml:"metadata>alias"`
}

type likelyDoc struct {
	Subtags []likelyEntry `xml:"likelySubtags>likelySubtag"`
}

func main() {
	dir := flag.String("cldr", "", "directory holding the CLDR supplemental XML")
	out := flag.String("out", "", "path of the Go file to write")
	flag.Parse()
	if *dir == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "usage: gencldr -cldr <dir> -out <file.go>")
		os.Exit(2)
	}

	var meta metadata
	read(filepath.Join(*dir, "supplementalMetadata.xml"), &meta)
	var likely likelyDoc
	read(filepath.Join(*dir, "likelySubtags.xml"), &likely)

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by tools/gencldr. DO NOT EDIT.

package engine

// CLDR alias and likely-subtags data, for canonicalising a language tag and
// for AddLikelySubtags/RemoveLikelySubtags. See tools/gencldr.
`)

	// Aliases whose type is not a unicode_language_id -- the BCP 47
	// grandfathered and extlang forms, "i-default" and "zh-cmn-Hans" and the
	// like -- are dropped. ECMA-402 validates against unicode_locale_id, under
	// which those tags are not structurally valid in the first place, so an
	// entry keyed on one could never match and would only be weight.
	langAliases := filterLanguage(meta.Alias.Language)
	emit(&b, "cldrLanguageAliasData",
		"language aliases: a unicode_language_id prefix and what replaces it.",
		langAliases)
	emit(&b, "cldrScriptAliasData", "script aliases.", simple(meta.Alias.Script))
	emit(&b, "cldrRegionAliasData",
		"region aliases. A replacement with several regions in it is resolved\n"+
			"// against the likely-subtags table at canonicalisation time, so the\n"+
			"// list is kept whole here.",
		simple(meta.Alias.Territory))
	emit(&b, "cldrVariantAliasData", "variant aliases.", simple(meta.Alias.Variant))

	// The -u- and -t- keyword values have their own aliases, one file per key
	// family under common/bcp47. Both spellings a deprecated value can have --
	// an `alias` attribute on the canonical type, and a `preferred` attribute
	// on the deprecated one -- end up as the same kind of entry here.
	kw := keywordAliases(filepath.Join(*dir, "bcp47"))
	for _, e := range meta.Alias.Subdivision {
		// A subdivision alias reaches the -u- extension through two keys, `sd`
		// (the subdivision itself) and `rg` (a region override spelled as one).
		// A subdivision that split has several replacements; UTS 35 takes the
		// first, and unlike a territory there is no likely-subtags tie-break.
		repl := strings.Fields(dash(e.Replacement))
		if len(repl) == 0 {
			continue
		}
		for _, key := range []string{"sd", "rg"} {
			kw = append(kw, [2]string{key + "/" + dash(e.Type), repl[0]})
		}
	}
	emit(&b, "cldrKeywordAliasData",
		"keyword value aliases, keyed \"<key>/<deprecated value>\".", kw)

	// zone.tab is the IANA database's own country-to-zone mapping, and it is
	// the only honest source for Intl.Locale.prototype.getTimeZones: an
	// identifier names a continent and a city, not a country, so the answer
	// cannot be read off the names.
	emit(&b, "cldrRegionZonesData",
		"IANA zones per ISO 3166 region, from zone.tab, space-separated.",
		regionZones(filepath.Join(*dir, "zone.tab")))

	// The collation types a -u-co keyword may name. Without this list any
	// well-formed type would be accepted, and "en-US-u-co-invalid" would
	// resolve to a collation that does not exist.
	emit(&b, "cldrCollationsData",
		"collation types, name -> \"\" (a set).", collationTypes(filepath.Join(*dir, "bcp47", "collation.xml")))

	emit(&b, "cldrNumberingSystemsData",
		"numbering systems with a simple digit mapping: name -> its ten digits.",
		numberingSystems(filepath.Join(*dir, "numberingSystems.xml")))

	// The three region tables Intl.Locale answers questions from. All three
	// key on a region, and the hour cycle also keys on a full locale, because
	// the clock travels with the language: Quebec writes 14:00 and Ontario
	// writes 2 PM, and both of them are CA.
	sup := filepath.Join(*dir, "supplementalData.xml")
	var supp supplemental
	read(sup, &supp)
	emit(&b, "cldrCalendarPreferenceData",
		"calendars a region prefers, best first, space-separated.",
		calendarPreference(supp))
	emit(&b, "cldrHourCycleData",
		"the clock a region or locale reads: h11, h12, h23 or h24.",
		hourCycles(supp))
	emit(&b, "cldrWeekData",
		"week data per region: first day, weekend start and weekend end as\n"+
			"// ISO weekday numbers, space-separated.",
		weekData(supp))

	// The likely-subtags value is written as a script+region pair whenever the
	// language is unchanged, which it is for all but the und-* entries. That is
	// most of the table and about a third of its bytes.
	var likelyPairs [][2]string
	for _, e := range likely.Subtags {
		from, to := dash(e.From), dash(e.To)
		lang := from
		if i := strings.IndexByte(from, '-'); i >= 0 {
			lang = from[:i]
		}
		if v, ok := strings.CutPrefix(to, lang+"-"); ok {
			to = v
		}
		likelyPairs = append(likelyPairs, [2]string{from, to})
	}
	emit(&b, "cldrLikelyData",
		"likely subtags. The value is the full tag when the language changes and\n"+
			"// the script-region remainder when it does not, which is the common case.",
		likelyPairs)

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "gofmt:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gencldr: %d language, %d script, %d region, %d variant, %d likely\n",
		len(langAliases), len(meta.Alias.Script), len(meta.Alias.Territory),
		len(meta.Alias.Variant), len(likelyPairs))
}

func read(path string, into any) {
	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()
	if err := xml.NewDecoder(f).Decode(into); err != nil {
		fmt.Fprintln(os.Stderr, path+":", err)
		os.Exit(1)
	}
}

func dash(s string) string { return strings.ReplaceAll(s, "_", "-") }

func simple(in []aliasEntry) [][2]string {
	out := make([][2]string, 0, len(in))
	for _, e := range in {
		out = append(out, [2]string{dash(e.Type), dash(e.Replacement)})
	}
	return out
}

// filterLanguage keeps the aliases whose type could actually occur in a
// structurally valid unicode_locale_id: a language subtag, optionally followed
// by a script, a region, or a variant.
func filterLanguage(in []aliasEntry) [][2]string {
	out := make([][2]string, 0, len(in))
	for _, e := range in {
		parts := strings.Split(dash(e.Type), "-")
		if !isLanguageSubtag(parts[0]) {
			continue
		}
		ok := true
		for _, p := range parts[1:] {
			if !isScriptSubtag(p) && !isRegionSubtag(p) && !isVariantSubtag(p) {
				ok = false
				break
			}
		}
		if ok {
			out = append(out, [2]string{dash(e.Type), dash(e.Replacement)})
		}
	}
	return out
}

func alpha(s string) bool {
	for i := 0; i < len(s); i++ {
		c := s[i] | 0x20
		if c < 'a' || c > 'z' {
			return false
		}
	}
	return len(s) > 0
}

func digits(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return len(s) > 0
}

func alnum(s string) bool {
	for i := 0; i < len(s); i++ {
		c := s[i] | 0x20
		if (c < 'a' || c > 'z') && (s[i] < '0' || s[i] > '9') {
			return false
		}
	}
	return len(s) > 0
}

func isLanguageSubtag(s string) bool {
	return alpha(s) && (len(s) == 2 || len(s) == 3 || (len(s) >= 5 && len(s) <= 8))
}
func isScriptSubtag(s string) bool { return len(s) == 4 && alpha(s) }
func isRegionSubtag(s string) bool {
	return (len(s) == 2 && alpha(s)) || (len(s) == 3 && digits(s))
}
func isVariantSubtag(s string) bool {
	return (len(s) >= 5 && len(s) <= 8 && alnum(s)) || (len(s) == 4 && digits(s[:1]) && alnum(s))
}

// emit writes one table as a sorted, newline-separated constant. Sorting is by
// key so the generated file has a stable diff across CLDR releases: a bumped
// version should show what changed, not a reshuffle.
func emit(b *strings.Builder, name, doc string, pairs [][2]string) {
	sort.Slice(pairs, func(i, j int) bool { return pairs[i][0] < pairs[j][0] })
	fmt.Fprintf(b, "\n// %s = %s\nconst %s = \"\" +\n", name, doc, name)
	seen := map[string]bool{}
	for _, p := range pairs {
		if seen[p[0]] {
			continue
		}
		seen[p[0]] = true
		fmt.Fprintf(b, "\t%q +\n", p[0]+" "+p[1]+"\n")
	}
	fmt.Fprintf(b, "\t\"\"\n")
}

// keyDoc is one common/bcp47 file: a handful of keys, each with its types.
type keyDoc struct {
	Keys []struct {
		Name  string `xml:"name,attr"`
		Types []struct {
			Name       string `xml:"name,attr"`
			Alias      string `xml:"alias,attr"`
			Deprecated string `xml:"deprecated,attr"`
			Preferred  string `xml:"preferred,attr"`
		} `xml:"type"`
	} `xml:"keyword>key"`
}

// keywordAliases reads every file in the bcp47 directory and returns the
// deprecated spellings of each keyword value, keyed "<key>/<value>".
func keywordAliases(dir string) [][2]string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var out [][2]string
	for _, f := range entries {
		if filepath.Ext(f.Name()) != ".xml" {
			continue
		}
		var doc keyDoc
		read(filepath.Join(dir, f.Name()), &doc)
		for _, k := range doc.Keys {
			for _, t := range k.Types {
				if t.Deprecated == "true" {
					// A deprecated type also carries the alias it replaced,
					// which points the wrong way: "islamicc" is deprecated in
					// favour of "islamic-civil" and lists it as an alias too.
					// Only the preferred direction is a canonicalisation.
					if t.Preferred != "" {
						out = append(out, [2]string{k.Name + "/" + t.Name, t.Preferred})
					}
					continue
				}
				for _, a := range strings.Fields(t.Alias) {
					out = append(out, [2]string{k.Name + "/" + strings.ToLower(a), t.Name})
				}
			}
		}
	}
	return out
}

// regionZones reads zone.tab: a country code, coordinates, a zone name, and an
// optional comment, one line per zone.
func regionZones(path string) [][2]string {
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	byRegion := map[string][]string{}
	var order []string
	for _, line := range strings.Split(string(data), "\n") {
		if line == "" || line[0] == '#' {
			continue
		}
		f := strings.Fields(line)
		if len(f) < 3 {
			continue
		}
		if _, seen := byRegion[f[0]]; !seen {
			order = append(order, f[0])
		}
		byRegion[f[0]] = append(byRegion[f[0]], f[2])
	}
	out := make([][2]string, 0, len(order))
	for _, r := range order {
		zones := byRegion[r]
		sort.Strings(zones)
		out = append(out, [2]string{r, strings.Join(zones, " ")})
	}
	return out
}

type supplemental struct {
	CalendarPreference []struct {
		Territories string `xml:"territories,attr"`
		Ordering    string `xml:"ordering,attr"`
	} `xml:"calendarPreferenceData>calendarPreference"`
	Hours []struct {
		Preferred string `xml:"preferred,attr"`
		Regions   string `xml:"regions,attr"`
	} `xml:"timeData>hours"`
	FirstDay []struct {
		Day         string `xml:"day,attr"`
		Territories string `xml:"territories,attr"`
		Alt         string `xml:"alt,attr"`
	} `xml:"weekData>firstDay"`
	WeekendStart []struct {
		Day         string `xml:"day,attr"`
		Territories string `xml:"territories,attr"`
		Alt         string `xml:"alt,attr"`
	} `xml:"weekData>weekendStart"`
	WeekendEnd []struct {
		Day         string `xml:"day,attr"`
		Territories string `xml:"territories,attr"`
		Alt         string `xml:"alt,attr"`
	} `xml:"weekData>weekendEnd"`
}

// isoWeekday is CLDR's day name as the number ECMA-402 reports, Monday first.
var isoWeekday = map[string]string{
	"mon": "1", "tue": "2", "wed": "3", "thu": "4", "fri": "5", "sat": "6", "sun": "7",
}

func calendarPreference(s supplemental) [][2]string {
	var out [][2]string
	for _, p := range s.CalendarPreference {
		for _, t := range strings.Fields(p.Territories) {
			out = append(out, [2]string{t, strings.Join(strings.Fields(p.Ordering), " ")})
		}
	}
	return out
}

// hourCycles maps CLDR's pattern letter to the hourCycle name: H is 0-23, h is
// 1-12, K is 0-11 and k is 1-24.
func hourCycles(s supplemental) [][2]string {
	cycle := map[string]string{"H": "h23", "h": "h12", "K": "h11", "k": "h24"}
	var out [][2]string
	for _, h := range s.Hours {
		c, ok := cycle[h.Preferred]
		if !ok {
			continue
		}
		for _, r := range strings.Fields(h.Regions) {
			out = append(out, [2]string{dash(r), c})
		}
	}
	return out
}

// weekData collects the three per-region week facts into one row each. The
// "variant" alternatives are skipped: they are a second opinion (the Shorter
// Oxford's view of when a British week starts), not the data.
func weekData(s supplemental) [][2]string {
	first, start, end := map[string]string{}, map[string]string{}, map[string]string{}
	collect := func(into map[string]string, day, territories, alt string) {
		if alt != "" {
			return
		}
		for _, t := range strings.Fields(territories) {
			into[t] = isoWeekday[day]
		}
	}
	for _, e := range s.FirstDay {
		collect(first, e.Day, e.Territories, e.Alt)
	}
	for _, e := range s.WeekendStart {
		collect(start, e.Day, e.Territories, e.Alt)
	}
	for _, e := range s.WeekendEnd {
		collect(end, e.Day, e.Territories, e.Alt)
	}
	seen := map[string]bool{}
	var regions []string
	for _, m := range []map[string]string{first, start, end} {
		for r := range m {
			if !seen[r] {
				seen[r], regions = true, append(regions, r)
			}
		}
	}
	sort.Strings(regions)
	var out [][2]string
	for _, r := range regions {
		pick := func(m map[string]string, fallback string) string {
			if v, ok := m[r]; ok {
				return v
			}
			return fallback
		}
		out = append(out, [2]string{r,
			pick(first, "") + " " + pick(start, "") + " " + pick(end, "")})
	}
	return out
}

type numberingDoc struct {
	Systems []struct {
		ID     string `xml:"id,attr"`
		Type   string `xml:"type,attr"`
		Digits string `xml:"digits,attr"`
	} `xml:"numberingSystems>numberingSystem"`
}

// numberingSystems keeps the systems that spell a number one digit at a time,
// which is what makes them a mapping rather than a rule. Their digits are
// usually ten consecutive code points, but not always: hanidec's zero is
// U+3007 and its one is U+4E00, half the Unicode range away, so the ten are
// written out rather than derived from the first.
func numberingSystems(path string) [][2]string {
	var doc numberingDoc
	read(path, &doc)
	var out [][2]string
	for _, s := range doc.Systems {
		if s.Type != "numeric" {
			continue
		}
		if len([]rune(s.Digits)) != 10 {
			continue
		}
		out = append(out, [2]string{s.ID, s.Digits})
	}
	return out
}

// collationTypes reads the collation key's types out of the bcp47 data,
// dropping the two that are not collations a caller may ask for by name.
func collationTypes(path string) [][2]string {
	var doc keyDoc
	read(path, &doc)
	var out [][2]string
	for _, k := range doc.Keys {
		if k.Name != "co" {
			continue
		}
		for _, t := range k.Types {
			if t.Name == "standard" || t.Name == "search" || t.Name == "" {
				continue
			}
			out = append(out, [2]string{t.Name, "x"})
		}
	}
	return out
}
