package engine

// Language tags: the `unicode_locale_id` grammar of UTS 35, and
// CanonicalizeUnicodeLocaleId.
//
// This replaces a regular expression that matched RFC 5646's `langtag`, which
// is a different and looser language: it accepted extlang sequences
// ("zh-hak-CN"), grandfathered tags ("i-klingon"), privateuse-only tags
// ("x-foo") and repeated subtags ("de-gregory-gregory"), all of which ECMA-402
// requires be rejected. It also did no canonicalisation at all, so
// `Intl.getCanonicalLocales("DE-de")` echoed the tag back unchanged.
//
// The alias and likely-subtags data is CLDR's, generated by tools/gencldr.

import (
	"sort"
	"strings"
	"sync"
)

// langTag is a parsed unicode_locale_id, in canonical case. Case normalisation
// happens during parsing because every later step -- alias lookup, sorting,
// comparison -- is defined on the normalised form.
type langTag struct {
	lang     string   // unicode_language_subtag, lowercase; "" only for a tag being built
	script   string   // Titlecase, or ""
	region   string   // uppercase letters or three digits, or ""
	variants []string // lowercase
	exts     []langExt
	private  []string // the subtags after "x-", lowercase
}

// langExt is one extension sequence: a singleton and everything up to the next
// singleton. 'x' is not stored here; it is private above.
type langExt struct {
	singleton byte
	subtags   []string
}

// ---- the tables ----

func parseAliasTable(data string) map[string]string {
	m := make(map[string]string, strings.Count(data, "\n"))
	for len(data) > 0 {
		line := data
		if i := strings.IndexByte(data, '\n'); i >= 0 {
			line, data = data[:i], data[i+1:]
		} else {
			data = ""
		}
		k, v, ok := strings.Cut(line, " ")
		if ok {
			m[k] = v
		}
	}
	return m
}

var (
	cldrLanguageAlias = sync.OnceValue(func() map[string]string { return parseAliasTable(cldrLanguageAliasData) })
	cldrScriptAlias   = sync.OnceValue(func() map[string]string { return parseAliasTable(cldrScriptAliasData) })
	cldrRegionAlias   = sync.OnceValue(func() map[string]string { return parseAliasTable(cldrRegionAliasData) })
	cldrVariantAlias  = sync.OnceValue(func() map[string]string { return parseAliasTable(cldrVariantAliasData) })
	cldrLikely        = sync.OnceValue(func() map[string]string { return parseAliasTable(cldrLikelyData) })
	cldrRegionZones   = sync.OnceValue(func() map[string]string { return parseAliasTable(cldrRegionZonesData) })
)

// ---- subtag shapes ----

func tagAlpha(s string) bool {
	for i := 0; i < len(s); i++ {
		c := s[i] | 0x20
		if c < 'a' || c > 'z' {
			return false
		}
	}
	return len(s) > 0
}

func tagDigits(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return len(s) > 0
}

func tagAlnum(s string) bool {
	for i := 0; i < len(s); i++ {
		c := s[i] | 0x20
		if (c < 'a' || c > 'z') && (s[i] < '0' || s[i] > '9') {
			return false
		}
	}
	return len(s) > 0
}

func isLangSubtag(s string) bool {
	return tagAlpha(s) && (len(s) == 2 || len(s) == 3 || (len(s) >= 5 && len(s) <= 8))
}
func isScriptSubtag(s string) bool { return len(s) == 4 && tagAlpha(s) }
func isRegionSubtag(s string) bool {
	return (len(s) == 2 && tagAlpha(s)) || (len(s) == 3 && tagDigits(s))
}
func isVariantSubtag(s string) bool {
	return (len(s) >= 5 && len(s) <= 8 && tagAlnum(s)) ||
		(len(s) == 4 && s[0] >= '0' && s[0] <= '9' && tagAlnum(s))
}

func tagTitle(s string) string {
	b := []byte(asciiLower(s))
	if len(b) > 0 && b[0] >= 'a' && b[0] <= 'z' {
		b[0] -= 'a' - 'A'
	}
	return string(b)
}

func asciiUpper(s string) string {
	b := []byte(s)
	for i, c := range b {
		if c >= 'a' && c <= 'z' {
			b[i] = c - ('a' - 'A')
		}
	}
	return string(b)
}

// ---- parsing ----

// parseLangTag implements IsStructurallyValidLanguageTag and returns the parsed
// tag in canonical case. It does not apply aliases; canonicalize does that.
func parseLangTag(s string) (*langTag, bool) {
	// The grammar is ASCII throughout, and a non-ASCII byte cannot be part of
	// any subtag. Checking here keeps every length test below honest, since a
	// multi-byte rune would otherwise count as several characters.
	for i := 0; i < len(s); i++ {
		if s[i] >= 0x80 {
			return nil, false
		}
	}
	if s == "" {
		return nil, false
	}
	parts := strings.Split(s, "-")
	for _, p := range parts {
		if p == "" {
			return nil, false // leading, trailing or doubled separator
		}
	}

	t := &langTag{}
	i := 0
	if !isLangSubtag(parts[i]) {
		return nil, false
	}
	t.lang = asciiLower(parts[i])
	i++
	if i < len(parts) && isScriptSubtag(parts[i]) && len(parts[i]) != 1 {
		t.script = tagTitle(parts[i])
		i++
	}
	if i < len(parts) && isRegionSubtag(parts[i]) && len(parts[i]) != 1 {
		t.region = asciiUpper(parts[i])
		i++
	}
	for i < len(parts) && isVariantSubtag(parts[i]) {
		v := asciiLower(parts[i])
		// A repeated variant is not a valid unicode_locale_id, and silently
		// keeping one would make two different tags canonicalise the same.
		for _, have := range t.variants {
			if have == v {
				return nil, false
			}
		}
		t.variants = append(t.variants, v)
		i++
	}

	// Extensions. Each is a singleton followed by at least one subtag, and no
	// singleton may appear twice.
	seen := map[byte]bool{}
	for i < len(parts) {
		p := parts[i]
		if len(p) != 1 || !tagAlnum(p) {
			return nil, false
		}
		sing := asciiLower(p)[0]
		if seen[sing] {
			return nil, false
		}
		seen[sing] = true
		i++
		start := i
		for i < len(parts) && len(parts[i]) != 1 {
			i++
		}
		body := make([]string, 0, i-start)
		for _, sub := range parts[start:i] {
			body = append(body, asciiLower(sub))
		}
		if sing == 'x' {
			// pu_extensions: subtags of 1-8 alphanumerics, and it runs to the
			// end of the tag, so a singleton after it is part of it.
			for j := start; j < len(parts); j++ {
				if len(parts[j]) < 1 || len(parts[j]) > 8 || !tagAlnum(parts[j]) {
					return nil, false
				}
			}
			if start == len(parts) {
				return nil, false
			}
			t.private = nil
			for _, sub := range parts[start:] {
				t.private = append(t.private, asciiLower(sub))
			}
			i = len(parts)
			break
		}
		if len(body) == 0 {
			return nil, false
		}
		if !validExtension(sing, body) {
			return nil, false
		}
		t.exts = append(t.exts, langExt{singleton: sing, subtags: body})
	}
	return t, true
}

// validExtension checks the body of one extension sequence. 'u' and 't' have
// their own grammars; every other singleton takes 2-8 alphanumeric subtags.
func validExtension(sing byte, body []string) bool {
	switch sing {
	case 'u':
		// attribute* keyword*, where an attribute is 3-8 alphanumerics and a
		// keyword is a 2-alphanumeric key followed by 3-8 alphanumeric types.
		i := 0
		for i < len(body) && len(body[i]) >= 3 && len(body[i]) <= 8 && tagAlnum(body[i]) {
			i++
		}
		for i < len(body) {
			// A keyword key is `alphanum alpha`: the second character must be a
			// letter, so "0c" is a key and "c0" and "00" are not.
			if len(body[i]) != 2 || !tagAlnum(body[i]) || !tagAlpha(body[i][1:]) {
				return false
			}
			i++
			for i < len(body) && len(body[i]) >= 3 && len(body[i]) <= 8 && tagAlnum(body[i]) {
				i++
			}
		}
		return true
	case 't':
		// (tlang tfield*) | tfield+, where a tfield key is an alphabetic
		// followed by a digit and its value is one or more 3-8 alphanumerics.
		i := 0
		if len(body) > 0 && !isTfieldKey(body[0]) {
			// A tlang: a unicode_language_id, which runs up to the first tfield
			// key. Reassembling and reparsing it is the honest way to check it
			// against the same grammar.
			j := 0
			for j < len(body) && !isTfieldKey(body[j]) {
				j++
			}
			if _, ok := parseLangTag(strings.Join(body[:j], "-")); !ok {
				return false
			}
			i = j
		}
		if i == 0 && len(body) == 0 {
			return false
		}
		for i < len(body) {
			if !isTfieldKey(body[i]) {
				return false
			}
			i++
			n := 0
			for i < len(body) && len(body[i]) >= 3 && len(body[i]) <= 8 && tagAlnum(body[i]) {
				i++
				n++
			}
			if n == 0 {
				return false
			}
		}
		return true
	default:
		for _, sub := range body {
			if len(sub) < 2 || len(sub) > 8 || !tagAlnum(sub) {
				return false
			}
		}
		return true
	}
}

func isTfieldKey(s string) bool {
	return len(s) == 2 && tagAlpha(s[:1]) && s[1] >= '0' && s[1] <= '9'
}

// ---- canonicalisation ----

// canonicalizeLangTag is CanonicalizeUnicodeLocaleId: structural validation
// followed by alias replacement and ordering. It reports false for a tag that
// is not structurally valid, which the caller turns into a RangeError.
func canonicalizeLangTag(s string) (string, bool) {
	t, ok := parseLangTag(s)
	if !ok {
		return "", false
	}
	t.canonicalize()
	return t.String(), true
}

// canonicalize applies the CLDR aliases and puts the subtags in order, in
// place.
func (t *langTag) canonicalize() {
	t.applyAliases()
	sort.Strings(t.variants)
	sort.Slice(t.exts, func(i, j int) bool { return t.exts[i].singleton < t.exts[j].singleton })
	for i := range t.exts {
		switch t.exts[i].singleton {
		case 'u':
			t.exts[i].subtags = canonicalizeUnicodeExt(t.exts[i].subtags)
		case 't':
			t.exts[i].subtags = canonicalizeTransformExt(t.exts[i].subtags)
		}
	}
}

// applyAliases replaces deprecated language, script, region and variant subtags
// with their CLDR preferred values.
func (t *langTag) applyAliases() {
	// The language alias is keyed on a unicode_language_id prefix, which may
	// carry a script, a region or one or more variants along with the language
	// ("sh", but also "sgn-GR", "zh-guoyu" and "und-hepburn-heploc"). The more
	// subtags a key has the more specific it is, so the rules are tried longest
	// first; and a key whose language is "und" matches any language, which is
	// how CLDR spells a rule about a variant alone.
	rules := cldrLangRules()
	if !t.applyLangRules(rules[t.lang]) {
		t.applyLangRules(rules["und"])
	}

	if repl, ok := cldrScriptAlias()[t.script]; ok {
		t.script = repl
	}
	if t.region != "" {
		if repl, ok := cldrRegionAlias()[t.region]; ok {
			t.region = t.pickRegion(repl)
		}
	}
	vars := cldrVariantAlias()
	for i, v := range t.variants {
		if repl, ok := vars[v]; ok {
			t.variants[i] = repl
		}
	}
}

// langAliasRule is one languageAlias entry with its key already parsed. n is
// how many subtags the key has, which is what "longest match wins" counts.
type langAliasRule struct {
	key  *langTag
	repl string
	n    int
}

// cldrLangRules groups the language aliases by the language they key on, so a
// tag consults a handful of rules rather than five hundred.
var cldrLangRules = sync.OnceValue(func() map[string][]langAliasRule {
	m := map[string][]langAliasRule{}
	for k, v := range cldrLanguageAlias() {
		kt, ok := parseLangTag(k)
		if !ok {
			continue
		}
		n := 1 + len(kt.variants)
		if kt.script != "" {
			n++
		}
		if kt.region != "" {
			n++
		}
		// A bare "und" would match every tag and replace its language, which
		// is not what the wildcard means.
		if kt.lang == "und" && n == 1 {
			continue
		}
		m[kt.lang] = append(m[kt.lang], langAliasRule{key: kt, repl: v, n: n})
	}
	for _, rs := range m {
		sort.SliceStable(rs, func(i, j int) bool { return rs[i].n > rs[j].n })
	}
	return m
})

// applyLangRules applies the first rule that matches, removing the subtags the
// key matched on and merging in the replacement. It reports whether one did.
func (t *langTag) applyLangRules(rules []langAliasRule) bool {
	for _, r := range rules {
		if r.key.script != "" && r.key.script != t.script {
			continue
		}
		if r.key.region != "" && r.key.region != t.region {
			continue
		}
		ok := true
		for _, v := range r.key.variants {
			if !tagContains(t.variants, v) {
				ok = false
				break
			}
		}
		if !ok {
			continue
		}
		if r.key.script != "" {
			t.script = ""
		}
		if r.key.region != "" {
			t.region = ""
		}
		for _, v := range r.key.variants {
			t.variants = removeString(t.variants, v)
		}
		t.mergeLanguageReplacement(r.repl)
		return true
	}
	return false
}

func removeString(ss []string, s string) []string {
	out := ss[:0:0]
	for _, v := range ss {
		if v != s {
			out = append(out, v)
		}
	}
	return out
}

// mergeLanguageReplacement applies a languageAlias replacement, which is itself
// a unicode_language_id: its language always wins, and its other subtags are
// taken only where the tag has none. "sh" becomes "sr-Latn", but "sh-Cyrl"
// becomes "sr-Cyrl" -- the script that was written down is not overruled by
// the one the alias suggests.
func (t *langTag) mergeLanguageReplacement(repl string) {
	r, ok := parseLangTag(repl)
	if !ok {
		return
	}
	// "und" on the replacement side means "leave the language alone" -- the
	// rule was about a variant, not about what language this is.
	if r.lang != "und" || t.lang == "" {
		t.lang = r.lang
	}
	if t.script == "" {
		t.script = r.script
	}
	if t.region == "" {
		t.region = r.region
	}
	for _, v := range r.variants {
		if !tagContains(t.variants, v) {
			t.variants = append(t.variants, v)
		}
	}
}

// pickRegion resolves a territoryAlias replacement. Most name one region; the
// ones that name several are the territories that split, and the rule is to
// take the one the language most likely belongs to and otherwise the first.
func (t *langTag) pickRegion(repl string) string {
	if !strings.Contains(repl, " ") {
		return repl
	}
	options := strings.Fields(repl)
	probe := &langTag{lang: t.lang, script: t.script}
	if m, ok := probe.maximized(); ok {
		for _, o := range options {
			if o == m.region {
				return o
			}
		}
	}
	return options[0]
}

func tagContains(ss []string, s string) bool {
	for _, v := range ss {
		if v == s {
			return true
		}
	}
	return false
}

// canonicalizeUnicodeExt orders the -u- extension: attributes sorted and
// deduplicated, then keywords sorted by key, with a type of "true" dropped
// because "-u-kn-true" and "-u-kn" mean the same thing and only one of them is
// canonical.
func canonicalizeUnicodeExt(body []string) []string {
	var attrs []string
	i := 0
	for i < len(body) && len(body[i]) != 2 {
		if !tagContains(attrs, body[i]) {
			attrs = append(attrs, body[i])
		}
		i++
	}
	sort.Strings(attrs)

	type kw struct {
		key   string
		types []string
	}
	var kws []kw
	for i < len(body) {
		k := kw{key: body[i]}
		i++
		for i < len(body) && len(body[i]) != 2 {
			k.types = append(k.types, body[i])
			i++
		}
		k.types = aliasKeywordValue(k.key, k.types)
		// A type of "true" is written as the bare key: "-u-kn-true" and
		// "-u-kn" are the same keyword and only one of them is canonical. The
		// alias step above is what turns "-u-kb-yes" into one of them.
		if len(k.types) == 1 && k.types[0] == "true" {
			k.types = nil
		}
		// A key repeated inside one extension keeps its first value, which is
		// what every other implementation does with it.
		dup := false
		for _, have := range kws {
			if have.key == k.key {
				dup = true
				break
			}
		}
		if !dup {
			kws = append(kws, k)
		}
	}
	sort.SliceStable(kws, func(a, b int) bool { return kws[a].key < kws[b].key })

	out := attrs
	for _, k := range kws {
		out = append(out, k.key)
		out = append(out, k.types...)
	}
	return out
}

// canonicalizeTransformExt orders the -t- extension: the tlang, if there is
// one, canonicalised as a language tag in its own right, then the fields sorted
// by key.
func canonicalizeTransformExt(body []string) []string {
	i := 0
	for i < len(body) && !isTfieldKey(body[i]) {
		i++
	}
	var out []string
	if i > 0 {
		if lt, ok := parseLangTag(strings.Join(body[:i], "-")); ok {
			lt.canonicalize()
			out = append(out, strings.Split(asciiLower(lt.String()), "-")...)
		} else {
			out = append(out, body[:i]...)
		}
	}
	type field struct {
		key    string
		values []string
	}
	var fields []field
	for i < len(body) {
		f := field{key: body[i]}
		i++
		for i < len(body) && !isTfieldKey(body[i]) {
			f.values = append(f.values, body[i])
			i++
		}
		fields = append(fields, f)
	}
	sort.SliceStable(fields, func(a, b int) bool { return fields[a].key < fields[b].key })
	for _, f := range fields {
		out = append(out, f.key)
		out = append(out, aliasKeywordValue(f.key, f.values)...)
	}
	return out
}

var cldrKeywordAlias = sync.OnceValue(func() map[string]string { return parseAliasTable(cldrKeywordAliasData) })

// aliasKeywordValue replaces a deprecated -u- or -t- keyword value with the one
// CLDR prefers: "-u-ca-ethiopic-amete-alem" is "-u-ca-ethioaa", "-u-ks-primary"
// is "-u-ks-level1". The value is looked up whole, because several of them are
// spelled across more than one subtag.
func aliasKeywordValue(key string, types []string) []string {
	if len(types) == 0 {
		return types
	}
	repl, ok := cldrKeywordAlias()[key+"/"+strings.Join(types, "-")]
	if !ok {
		return types
	}
	return strings.Split(repl, "-")
}

// String renders the tag. The private-use sequence is last by construction,
// which is also where the grammar puts it.
func (t *langTag) String() string {
	var b strings.Builder
	b.WriteString(t.lang)
	if t.script != "" {
		b.WriteByte('-')
		b.WriteString(t.script)
	}
	if t.region != "" {
		b.WriteByte('-')
		b.WriteString(t.region)
	}
	for _, v := range t.variants {
		b.WriteByte('-')
		b.WriteString(v)
	}
	for _, e := range t.exts {
		b.WriteByte('-')
		b.WriteByte(e.singleton)
		for _, s := range e.subtags {
			b.WriteByte('-')
			b.WriteString(s)
		}
	}
	if len(t.private) > 0 {
		b.WriteString("-x")
		for _, s := range t.private {
			b.WriteByte('-')
			b.WriteString(s)
		}
	}
	return b.String()
}

// languageID is the tag without its extensions: what maximize and minimize
// operate on.
func (t *langTag) languageID() string {
	u := &langTag{lang: t.lang, script: t.script, region: t.region, variants: t.variants}
	return u.String()
}

// ---- likely subtags ----

// likelyLookup reads the CLDR table, undoing the generator's shorthand: a value
// with no language of its own inherits the key's.
func likelyLookup(key string) (string, bool) {
	v, ok := cldrLikely()[key]
	if !ok {
		return "", false
	}
	lang, _, _ := strings.Cut(key, "-")
	if strings.Count(v, "-") == 1 {
		return lang + "-" + v, true
	}
	return v, true
}

// maximized is AddLikelySubtags: the language, script and region CLDR says a
// tag most probably denotes. Variants and extensions ride along unchanged.
func (t *langTag) maximized() (*langTag, bool) {
	lang := t.lang
	if lang == "" {
		lang = "und"
	}
	// The four lookups of AddLikelySubtags, most specific first. A candidate
	// whose distinguishing subtag is absent is skipped rather than collapsed
	// into the bare language: with no region, "lang-region" spells "lang" and
	// answers the last question two steps early, which is how "ru-Armn" came
	// back as ru-Armn-RU instead of ru-Armn-AM.
	keys := []string{tagJoin(lang, t.script, t.region)}
	if t.region != "" {
		keys = append(keys, tagJoin(lang, "", t.region))
	}
	if t.script != "" {
		keys = append(keys, tagJoin(lang, t.script, ""))
	}
	keys = append(keys, lang)
	for _, key := range keys {
		got, ok := likelyLookup(key)
		if !ok {
			continue
		}
		m, ok := parseLangTag(got)
		if !ok {
			continue
		}
		out := *t
		out.lang = m.lang
		out.script = m.script
		out.region = m.region
		// What was written down wins over what was inferred.
		if t.script != "" {
			out.script = t.script
		}
		if t.region != "" {
			out.region = t.region
		}
		if t.lang != "" && t.lang != "und" {
			out.lang = t.lang
		}
		return &out, true
	}
	return nil, false
}

// minimized is RemoveLikelySubtags, defined as the shortest tag that maximizes
// back to the same thing. Trying the three candidates in this order is the
// algorithm, not an optimisation of it.
func (t *langTag) minimized() (*langTag, bool) {
	max, ok := t.maximized()
	if !ok {
		return nil, false
	}
	// The comparison is on language, script and region alone. Variants ride
	// along untouched and would otherwise make every candidate look wrong:
	// "en-fonipa" maximizes to "en-Latn-US-fonipa", and "en" maximizes to
	// "en-Latn-US", which is the same answer to the question being asked.
	full := (&langTag{lang: max.lang, script: max.script, region: max.region}).String()
	for _, cand := range []*langTag{
		{lang: max.lang},
		{lang: max.lang, region: max.region},
		{lang: max.lang, script: max.script},
	} {
		m, ok := cand.maximized()
		if ok && (&langTag{lang: m.lang, script: m.script, region: m.region}).String() == full {
			out := *t
			out.lang = cand.lang
			out.script = cand.script
			out.region = cand.region
			return &out, true
		}
	}
	out := *t
	out.lang = max.lang
	out.script = max.script
	out.region = max.region
	return &out, true
}

func tagJoin(parts ...string) string {
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		if b.Len() > 0 {
			b.WriteByte('-')
		}
		b.WriteString(p)
	}
	return b.String()
}

// ---- the -u- extension, as a keyword map ----

// uExt returns the Unicode extension sequence, or nil.
func (t *langTag) uExt() *langExt {
	for i := range t.exts {
		if t.exts[i].singleton == 'u' {
			return &t.exts[i]
		}
	}
	return nil
}

// uKeyword reads one -u- keyword, reporting whether it was there at all. A
// keyword written without a type ("-u-kf") reads back as the empty string,
// which is a different answer from absent: the getters return undefined for
// one and "" for the other.
func (t *langTag) uKeyword(key string) (string, bool) {
	e := t.uExt()
	if e == nil {
		return "", false
	}
	for i := 0; i < len(e.subtags); i++ {
		if len(e.subtags[i]) != 2 {
			continue
		}
		if e.subtags[i] != key {
			continue
		}
		var types []string
		for j := i + 1; j < len(e.subtags) && len(e.subtags[j]) != 2; j++ {
			types = append(types, e.subtags[j])
		}
		return strings.Join(types, "-"), true
	}
	return "", false
}

// setUKeyword installs or replaces one -u- keyword, creating the extension if
// there is none. A value of "true" is stored as the bare key, which is its
// canonical spelling.
func (t *langTag) setUKeyword(key, value string) {
	e := t.uExt()
	if e == nil {
		t.exts = append(t.exts, langExt{singleton: 'u'})
		sort.Slice(t.exts, func(i, j int) bool { return t.exts[i].singleton < t.exts[j].singleton })
		e = t.uExt()
	}
	out := make([]string, 0, len(e.subtags)+2)
	for i := 0; i < len(e.subtags); {
		if len(e.subtags[i]) == 2 && e.subtags[i] == key {
			i++
			for i < len(e.subtags) && len(e.subtags[i]) != 2 {
				i++
			}
			continue
		}
		out = append(out, e.subtags[i])
		i++
	}
	out = append(out, key)
	if value != "true" && value != "" {
		out = append(out, strings.Split(value, "-")...)
	}
	e.subtags = canonicalizeUnicodeExt(out)
}

// dropUKeyword removes a keyword, and the extension with it if it was the last
// thing in it -- an empty "-u-" is not a valid tag.
func (t *langTag) dropUKeyword(key string) {
	e := t.uExt()
	if e == nil {
		return
	}
	out := e.subtags[:0:0]
	for i := 0; i < len(e.subtags); {
		if len(e.subtags[i]) == 2 && e.subtags[i] == key {
			i++
			for i < len(e.subtags) && len(e.subtags[i]) != 2 {
				i++
			}
			continue
		}
		out = append(out, e.subtags[i])
		i++
	}
	if len(out) == 0 {
		for i := range t.exts {
			if t.exts[i].singleton == 'u' {
				t.exts = append(t.exts[:i], t.exts[i+1:]...)
				return
			}
		}
		return
	}
	e.subtags = out
}
