// Code generated by tools/genops from ant include/silver/opcode.h. DO NOT EDIT.

package engine

// OpFormat classifies an opcode's inline operand encoding (ant OP_FMT).
type OpFormat uint8

const (
	FmtNone OpFormat = iota
	FmtU8
	FmtI8
	FmtU16
	FmtI16
	FmtU32
	FmtI32
	FmtAtom
	FmtAtomU8
	FmtLabel
	FmtLabel8
	FmtLoc
	FmtLoc8
	FmtLocAtom
	FmtArg
	FmtConst
	FmtConst8
	FmtNpop
	FmtVarRef
)

var opFormatNames = [...]string{
	FmtNone:    "none",
	FmtU8:      "u8",
	FmtI8:      "i8",
	FmtU16:     "u16",
	FmtI16:     "i16",
	FmtU32:     "u32",
	FmtI32:     "i32",
	FmtAtom:    "atom",
	FmtAtomU8:  "atom_u8",
	FmtLabel:   "label",
	FmtLabel8:  "label8",
	FmtLoc:     "loc",
	FmtLoc8:    "loc8",
	FmtLocAtom: "loc_atom",
	FmtArg:     "arg",
	FmtConst:   "const",
	FmtConst8:  "const8",
	FmtNpop:    "npop",
	FmtVarRef:  "var_ref",
}

func (f OpFormat) String() string { return opFormatNames[f] }

// Opcode is a Silver bytecode operation (ant OP_DEF).
type Opcode uint8

const (
	OpInvalid Opcode = iota
	OpConst
	OpConstI8
	OpConst8
	OpUndef
	OpNull
	OpTrue
	OpFalse
	OpThis
	OpGlobal
	OpObject
	OpPrivateToken
	OpArray
	OpSetBrand
	OpRegexp
	OpClosure
	OpPop
	OpDup
	OpDup2
	OpSwap
	OpRot3l
	OpRot3r
	OpNip
	OpNip2
	OpInsert2
	OpInsert3
	OpSwapUnder
	OpRot4Under
	OpGetLocal
	OpPutLocal
	OpSetLocal
	OpGetLocal8
	OpPutLocal8
	OpSetLocal8
	OpSetLocalUndef
	OpGetLocalChk
	OpPutLocalChk
	OpGetSlotRaw
	OpGetArg
	OpPutArg
	OpSetArg
	OpRest
	OpGetUpval
	OpPutUpval
	OpSetUpval
	OpCloseUpval
	OpGetGlobal
	OpGetGlobalUndef
	OpPutGlobal
	OpGetField
	OpGetField2
	OpPutField
	OpGetElem
	OpGetElem2
	OpPutElem
	OpDefineField
	OpGetLength
	OpGetFieldOpt
	OpGetElemOpt
	OpGetPrivate
	OpGetPrivateOpt
	OpPutPrivate
	OpDefPrivate
	OpHasPrivate
	OpGetSuper
	OpGetSuperVal
	OpPutSuperVal
	OpAdd
	OpSub
	OpMul
	OpDiv
	OpAddNum
	OpSubNum
	OpMulNum
	OpDivNum
	OpMod
	OpExp
	OpNeg
	OpUplus
	OpInc
	OpDec
	OpPostInc
	OpPostDec
	OpIncLocal
	OpDecLocal
	OpAddLocal
	OpStrAppendLocal
	OpStrAlcSnapshot
	OpStrFlushLocal
	OpEq
	OpNe
	OpSeq
	OpSne
	OpLt
	OpLe
	OpGt
	OpGe
	OpInstanceof
	OpIn
	OpIsNullish
	OpIsUndefOrNull
	OpBand
	OpBor
	OpBxor
	OpBnot
	OpShl
	OpShr
	OpUshr
	OpNot
	OpTypeof
	OpVoid
	OpDelete
	OpDeleteVar
	OpJmp
	OpJmpFalse
	OpJmpTrue
	OpJmpFalsePeek
	OpJmpTruePeek
	OpJmpNotNullish
	OpJmp8
	OpJmpFalse8
	OpJmpTrue8
	OpCall
	OpCallMethod
	OpCallIsProto
	OpCallArrayIncludes
	OpReLiteralExec
	OpStrReLiteralReplace
	OpReExecTruthy
	OpTailCall
	OpTailCallMethod
	OpNew
	OpApply
	OpSuperApply
	OpNewApply
	OpEval
	OpReturn
	OpReturnUndef
	OpReturnAsync
	OpCheckCtor
	OpCheckCtorRet
	OpHalt
	OpThrow
	OpThrowError
	OpTryPush
	OpTryPushFinally
	OpTryPop
	OpCatch
	OpFinally
	OpFinallyRet
	OpFinallyDiscard
	OpUnwindJmp
	OpNipCatch
	OpUsingPush
	OpUsingPushAsync
	OpDisposeResource
	OpDisposeResourceAsync
	OpUsingDispose
	OpUsingDisposeAsync
	OpUsingDisposeSuppressed
	OpUsingDisposeAsyncSuppressed
	OpForIn
	OpForOf
	OpForAwaitOf
	OpIterNext
	OpIterGetValue
	OpIterClose
	OpIterCall
	OpAwaitIterNext
	OpDestructureInit
	OpDestructureNext
	OpDestructureRest
	OpDestructureClose
	OpAwait
	OpYield
	OpYieldStarInit
	OpYieldStarNext
	OpYieldStarThrow
	OpYieldStarReturn
	OpSpread
	OpDefineMethod
	OpDefineMethodComp
	OpSetName
	OpSetNameComp
	OpSetProto
	OpSetHomeObj
	OpAppend
	OpCopyDataProps
	OpDefineClass
	OpDefineClassComp
	OpToObject
	OpToPropkey
	OpIsUndef
	OpIsNull
	OpImport
	OpImportSource
	OpImportSync
	OpImportDefault
	OpImportNamed
	OpExport
	OpExportAll
	OpEnterWith
	OpExitWith
	OpWithGetVar
	OpWithPutVar
	OpWithDelVar
	OpSpecialObj
	OpEmpty
	OpDebugger
	OpNop
	OpPutConst
	OpLabel
	OpLineNum
	OpColNum
	// OpChkCtor pops a class-heritage value and throws a TypeError unless it is
	// null or a constructor (ClassDefinitionEvaluation's IsConstructor check).
	OpChkCtor
	// OpChkProto pops a superclass's .prototype and throws a TypeError unless it
	// is an Object or null (the protoParent check).
	OpChkProto
	// OpImportDefer is `import defer * as ns`: the module is already linked, so
	// this only asks for its namespace WITHOUT evaluating it. What comes back is
	// the deferred namespace, which runs the module the first time it is asked
	// about a string key.
	OpImportDefer
	// OpImportDeferDyn is `import.defer(spec, options)`: like a dynamic import,
	// except that what the promise settles with is the deferred namespace and
	// only the module's asynchronous dependencies are evaluated.
	OpImportDeferDyn

	NumOpcodes = 218
)

// Per-opcode JIT metadata flags (ant OP_FLAG / SV_OPF_*).
const (
	OpfJitEligible uint32 = 1 << iota
	OpfJitInlineable
	OpfJitNeedsArgsBuf
	OpfJitNeedsCloseUpval
	OpfJitLocalNumericBailout
	OpfJitNeedsBailout
	OpfJitNeedsIcEpoch
	OpfJitNeedsIncLocal
	OpfJitBranch32
	OpfJitOsrBackedge
	OpfJitBranch8
	OpfJitNeedsTcoArgs
	OpfJitNeedsIterRoots
)

type opInfo struct {
	Name   string
	Size   uint8
	NPop   uint8
	NPush  uint8
	Format OpFormat
	Flags  uint32
}

var opTable = [NumOpcodes]opInfo{
	OpInvalid:                     {Name: "INVALID", Size: 1, NPop: 0, NPush: 0, Format: FmtNone, Flags: 0},
	OpConst:                       {Name: "CONST", Size: 5, NPop: 0, NPush: 1, Format: FmtConst, Flags: OpfJitEligible | OpfJitInlineable},
	OpConstI8:                     {Name: "CONST_I8", Size: 2, NPop: 0, NPush: 1, Format: FmtI8, Flags: OpfJitEligible | OpfJitInlineable},
	OpConst8:                      {Name: "CONST8", Size: 2, NPop: 0, NPush: 1, Format: FmtConst8, Flags: OpfJitEligible | OpfJitInlineable},
	OpUndef:                       {Name: "UNDEF", Size: 1, NPop: 0, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpNull:                        {Name: "NULL", Size: 1, NPop: 0, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpTrue:                        {Name: "TRUE", Size: 1, NPop: 0, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpFalse:                       {Name: "FALSE", Size: 1, NPop: 0, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpThis:                        {Name: "THIS", Size: 1, NPop: 0, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpGlobal:                      {Name: "GLOBAL", Size: 1, NPop: 0, NPush: 1, Format: FmtNone, Flags: 0},
	OpObject:                      {Name: "OBJECT", Size: 1, NPop: 0, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpPrivateToken:                {Name: "PRIVATE_TOKEN", Size: 5, NPop: 0, NPush: 1, Format: FmtU32, Flags: 0},
	OpArray:                       {Name: "ARRAY", Size: 3, NPop: 0, NPush: 1, Format: FmtNpop, Flags: OpfJitEligible | OpfJitNeedsArgsBuf},
	OpSetBrand:                    {Name: "SET_BRAND", Size: 2, NPop: 1, NPush: 1, Format: FmtU8, Flags: 0},
	OpRegexp:                      {Name: "REGEXP", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: 0},
	OpClosure:                     {Name: "CLOSURE", Size: 5, NPop: 0, NPush: 1, Format: FmtConst, Flags: OpfJitEligible | OpfJitNeedsCloseUpval},
	OpPop:                         {Name: "POP", Size: 1, NPop: 1, NPush: 0, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpDup:                         {Name: "DUP", Size: 1, NPop: 1, NPush: 2, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpDup2:                        {Name: "DUP2", Size: 1, NPop: 2, NPush: 4, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpSwap:                        {Name: "SWAP", Size: 1, NPop: 2, NPush: 2, Format: FmtNone, Flags: OpfJitEligible},
	OpRot3l:                       {Name: "ROT3L", Size: 1, NPop: 3, NPush: 3, Format: FmtNone, Flags: OpfJitEligible},
	OpRot3r:                       {Name: "ROT3R", Size: 1, NPop: 3, NPush: 3, Format: FmtNone, Flags: 0},
	OpNip:                         {Name: "NIP", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpNip2:                        {Name: "NIP2", Size: 1, NPop: 3, NPush: 1, Format: FmtNone, Flags: 0},
	OpInsert2:                     {Name: "INSERT2", Size: 1, NPop: 2, NPush: 3, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpInsert3:                     {Name: "INSERT3", Size: 1, NPop: 3, NPush: 4, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpSwapUnder:                   {Name: "SWAP_UNDER", Size: 1, NPop: 3, NPush: 3, Format: FmtNone, Flags: 0},
	OpRot4Under:                   {Name: "ROT4_UNDER", Size: 1, NPop: 4, NPush: 4, Format: FmtNone, Flags: 0},
	OpGetLocal:                    {Name: "GET_LOCAL", Size: 3, NPop: 0, NPush: 1, Format: FmtLoc, Flags: OpfJitEligible | OpfJitInlineable},
	OpPutLocal:                    {Name: "PUT_LOCAL", Size: 3, NPop: 1, NPush: 0, Format: FmtLoc, Flags: OpfJitEligible | OpfJitInlineable | OpfJitLocalNumericBailout},
	OpSetLocal:                    {Name: "SET_LOCAL", Size: 3, NPop: 1, NPush: 1, Format: FmtLoc, Flags: OpfJitEligible | OpfJitInlineable | OpfJitLocalNumericBailout},
	OpGetLocal8:                   {Name: "GET_LOCAL8", Size: 2, NPop: 0, NPush: 1, Format: FmtLoc8, Flags: OpfJitEligible | OpfJitInlineable},
	OpPutLocal8:                   {Name: "PUT_LOCAL8", Size: 2, NPop: 1, NPush: 0, Format: FmtLoc8, Flags: OpfJitEligible | OpfJitInlineable | OpfJitLocalNumericBailout},
	OpSetLocal8:                   {Name: "SET_LOCAL8", Size: 2, NPop: 1, NPush: 1, Format: FmtLoc8, Flags: OpfJitEligible | OpfJitInlineable | OpfJitLocalNumericBailout},
	OpSetLocalUndef:               {Name: "SET_LOCAL_UNDEF", Size: 3, NPop: 0, NPush: 0, Format: FmtLoc, Flags: OpfJitEligible},
	OpGetLocalChk:                 {Name: "GET_LOCAL_CHK", Size: 7, NPop: 0, NPush: 1, Format: FmtLocAtom, Flags: 0},
	OpPutLocalChk:                 {Name: "PUT_LOCAL_CHK", Size: 7, NPop: 1, NPush: 0, Format: FmtLocAtom, Flags: 0},
	OpGetSlotRaw:                  {Name: "GET_SLOT_RAW", Size: 3, NPop: 0, NPush: 1, Format: FmtLoc, Flags: OpfJitEligible},
	OpGetArg:                      {Name: "GET_ARG", Size: 3, NPop: 0, NPush: 1, Format: FmtArg, Flags: OpfJitEligible | OpfJitInlineable},
	OpPutArg:                      {Name: "PUT_ARG", Size: 3, NPop: 1, NPush: 0, Format: FmtArg, Flags: 0},
	OpSetArg:                      {Name: "SET_ARG", Size: 3, NPop: 1, NPush: 1, Format: FmtArg, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpRest:                        {Name: "REST", Size: 3, NPop: 0, NPush: 1, Format: FmtU16, Flags: OpfJitEligible},
	OpGetUpval:                    {Name: "GET_UPVAL", Size: 3, NPop: 0, NPush: 1, Format: FmtVarRef, Flags: OpfJitEligible | OpfJitInlineable},
	OpPutUpval:                    {Name: "PUT_UPVAL", Size: 3, NPop: 1, NPush: 0, Format: FmtVarRef, Flags: OpfJitEligible},
	OpSetUpval:                    {Name: "SET_UPVAL", Size: 3, NPop: 1, NPush: 1, Format: FmtVarRef, Flags: OpfJitEligible},
	OpCloseUpval:                  {Name: "CLOSE_UPVAL", Size: 3, NPop: 0, NPush: 0, Format: FmtLoc, Flags: OpfJitEligible | OpfJitNeedsCloseUpval},
	OpGetGlobal:                   {Name: "GET_GLOBAL", Size: 7, NPop: 0, NPush: 1, Format: FmtAtom, Flags: OpfJitEligible | OpfJitInlineable},
	OpGetGlobalUndef:              {Name: "GET_GLOBAL_UNDEF", Size: 7, NPop: 0, NPush: 1, Format: FmtAtom, Flags: OpfJitEligible},
	OpPutGlobal:                   {Name: "PUT_GLOBAL", Size: 5, NPop: 1, NPush: 0, Format: FmtAtom, Flags: OpfJitEligible},
	OpGetField:                    {Name: "GET_FIELD", Size: 7, NPop: 1, NPush: 1, Format: FmtAtom, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsIcEpoch},
	OpGetField2:                   {Name: "GET_FIELD2", Size: 7, NPop: 1, NPush: 2, Format: FmtAtom, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsIcEpoch},
	OpPutField:                    {Name: "PUT_FIELD", Size: 7, NPop: 2, NPush: 0, Format: FmtAtom, Flags: OpfJitEligible | OpfJitNeedsIcEpoch},
	OpGetElem:                     {Name: "GET_ELEM", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpGetElem2:                    {Name: "GET_ELEM2", Size: 1, NPop: 2, NPush: 2, Format: FmtNone, Flags: OpfJitEligible},
	OpPutElem:                     {Name: "PUT_ELEM", Size: 1, NPop: 3, NPush: 0, Format: FmtNone, Flags: OpfJitEligible},
	OpDefineField:                 {Name: "DEFINE_FIELD", Size: 5, NPop: 2, NPush: 1, Format: FmtAtom, Flags: OpfJitEligible},
	OpGetLength:                   {Name: "GET_LENGTH", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpGetFieldOpt:                 {Name: "GET_FIELD_OPT", Size: 7, NPop: 1, NPush: 1, Format: FmtAtom, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsIcEpoch},
	OpGetElemOpt:                  {Name: "GET_ELEM_OPT", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpGetPrivate:                  {Name: "GET_PRIVATE", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpGetPrivateOpt:               {Name: "GET_PRIVATE_OPT", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: 0},
	OpPutPrivate:                  {Name: "PUT_PRIVATE", Size: 1, NPop: 3, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpDefPrivate:                  {Name: "DEF_PRIVATE", Size: 2, NPop: 3, NPush: 1, Format: FmtU8, Flags: 0},
	OpHasPrivate:                  {Name: "HAS_PRIVATE", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: 0},
	OpGetSuper:                    {Name: "GET_SUPER", Size: 1, NPop: 0, NPush: 1, Format: FmtNone, Flags: 0},
	OpGetSuperVal:                 {Name: "GET_SUPER_VAL", Size: 1, NPop: 3, NPush: 1, Format: FmtNone, Flags: 0},
	OpPutSuperVal:                 {Name: "PUT_SUPER_VAL", Size: 1, NPop: 4, NPush: 1, Format: FmtNone, Flags: 0},
	OpAdd:                         {Name: "ADD", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpSub:                         {Name: "SUB", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpMul:                         {Name: "MUL", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpDiv:                         {Name: "DIV", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpAddNum:                      {Name: "ADD_NUM", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpSubNum:                      {Name: "SUB_NUM", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpMulNum:                      {Name: "MUL_NUM", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpDivNum:                      {Name: "DIV_NUM", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpMod:                         {Name: "MOD", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpExp:                         {Name: "EXP", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: 0},
	OpNeg:                         {Name: "NEG", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpUplus:                       {Name: "UPLUS", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: 0},
	OpInc:                         {Name: "INC", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsBailout | OpfJitNeedsIncLocal},
	OpDec:                         {Name: "DEC", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsBailout | OpfJitNeedsIncLocal},
	OpPostInc:                     {Name: "POST_INC", Size: 1, NPop: 1, NPush: 2, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsIncLocal},
	OpPostDec:                     {Name: "POST_DEC", Size: 1, NPop: 1, NPush: 2, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsBailout | OpfJitNeedsIncLocal},
	OpIncLocal:                    {Name: "INC_LOCAL", Size: 2, NPop: 0, NPush: 0, Format: FmtLoc8, Flags: OpfJitEligible | OpfJitNeedsIncLocal},
	OpDecLocal:                    {Name: "DEC_LOCAL", Size: 2, NPop: 0, NPush: 0, Format: FmtLoc8, Flags: OpfJitEligible | OpfJitNeedsIncLocal},
	OpAddLocal:                    {Name: "ADD_LOCAL", Size: 2, NPop: 1, NPush: 0, Format: FmtLoc8, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpStrAppendLocal:              {Name: "STR_APPEND_LOCAL", Size: 3, NPop: 1, NPush: 0, Format: FmtLoc, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpStrAlcSnapshot:              {Name: "STR_ALC_SNAPSHOT", Size: 3, NPop: 2, NPush: 0, Format: FmtLoc, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpStrFlushLocal:               {Name: "STR_FLUSH_LOCAL", Size: 3, NPop: 0, NPush: 0, Format: FmtLoc, Flags: OpfJitNeedsBailout},
	OpEq:                          {Name: "EQ", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpNe:                          {Name: "NE", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpSeq:                         {Name: "SEQ", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpSne:                         {Name: "SNE", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpLt:                          {Name: "LT", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpLe:                          {Name: "LE", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpGt:                          {Name: "GT", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpGe:                          {Name: "GE", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable | OpfJitNeedsBailout},
	OpInstanceof:                  {Name: "INSTANCEOF", Size: 3, NPop: 2, NPush: 1, Format: FmtU16, Flags: OpfJitEligible | OpfJitNeedsIcEpoch},
	OpIn:                          {Name: "IN", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpIsNullish:                   {Name: "IS_NULLISH", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: 0},
	OpIsUndefOrNull:               {Name: "IS_UNDEF_OR_NULL", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpBand:                        {Name: "BAND", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpBor:                         {Name: "BOR", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpBxor:                        {Name: "BXOR", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpBnot:                        {Name: "BNOT", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpShl:                         {Name: "SHL", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpShr:                         {Name: "SHR", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpUshr:                        {Name: "USHR", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpNot:                         {Name: "NOT", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpTypeof:                      {Name: "TYPEOF", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsBailout},
	OpVoid:                        {Name: "VOID", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpDelete:                      {Name: "DELETE", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpDeleteVar:                   {Name: "DELETE_VAR", Size: 5, NPop: 0, NPush: 1, Format: FmtAtom, Flags: 0},
	OpJmp:                         {Name: "JMP", Size: 5, NPop: 0, NPush: 0, Format: FmtLabel, Flags: OpfJitEligible | OpfJitInlineable | OpfJitBranch32 | OpfJitOsrBackedge},
	OpJmpFalse:                    {Name: "JMP_FALSE", Size: 5, NPop: 1, NPush: 0, Format: FmtLabel, Flags: OpfJitEligible | OpfJitInlineable | OpfJitBranch32 | OpfJitOsrBackedge},
	OpJmpTrue:                     {Name: "JMP_TRUE", Size: 5, NPop: 1, NPush: 0, Format: FmtLabel, Flags: OpfJitEligible | OpfJitInlineable | OpfJitBranch32 | OpfJitOsrBackedge},
	OpJmpFalsePeek:                {Name: "JMP_FALSE_PEEK", Size: 5, NPop: 1, NPush: 1, Format: FmtLabel, Flags: OpfJitEligible | OpfJitInlineable | OpfJitBranch32 | OpfJitOsrBackedge},
	OpJmpTruePeek:                 {Name: "JMP_TRUE_PEEK", Size: 5, NPop: 1, NPush: 1, Format: FmtLabel, Flags: OpfJitEligible | OpfJitInlineable | OpfJitBranch32 | OpfJitOsrBackedge},
	OpJmpNotNullish:               {Name: "JMP_NOT_NULLISH", Size: 5, NPop: 1, NPush: 1, Format: FmtLabel, Flags: OpfJitEligible | OpfJitInlineable | OpfJitBranch32 | OpfJitOsrBackedge},
	OpJmp8:                        {Name: "JMP8", Size: 2, NPop: 0, NPush: 0, Format: FmtLabel8, Flags: OpfJitEligible | OpfJitBranch8 | OpfJitOsrBackedge},
	OpJmpFalse8:                   {Name: "JMP_FALSE8", Size: 2, NPop: 1, NPush: 0, Format: FmtLabel8, Flags: OpfJitEligible | OpfJitInlineable | OpfJitBranch8 | OpfJitOsrBackedge},
	OpJmpTrue8:                    {Name: "JMP_TRUE8", Size: 2, NPop: 1, NPush: 0, Format: FmtLabel8, Flags: OpfJitEligible | OpfJitInlineable | OpfJitBranch8 | OpfJitOsrBackedge},
	OpCall:                        {Name: "CALL", Size: 3, NPop: 1, NPush: 1, Format: FmtNpop, Flags: OpfJitEligible | OpfJitNeedsArgsBuf},
	OpCallMethod:                  {Name: "CALL_METHOD", Size: 3, NPop: 2, NPush: 1, Format: FmtNpop, Flags: OpfJitEligible | OpfJitNeedsArgsBuf},
	OpCallIsProto:                 {Name: "CALL_IS_PROTO", Size: 3, NPop: 3, NPush: 1, Format: FmtU16, Flags: OpfJitEligible | OpfJitNeedsIcEpoch},
	OpCallArrayIncludes:           {Name: "CALL_ARRAY_INCLUDES", Size: 3, NPop: 2, NPush: 1, Format: FmtNpop, Flags: OpfJitEligible | OpfJitNeedsArgsBuf},
	OpReLiteralExec:               {Name: "RE_LITERAL_EXEC", Size: 1, NPop: 3, NPush: 1, Format: FmtNone, Flags: 0},
	OpStrReLiteralReplace:         {Name: "STR_RE_LITERAL_REPLACE", Size: 1, NPop: 4, NPush: 1, Format: FmtNone, Flags: 0},
	OpReExecTruthy:                {Name: "RE_EXEC_TRUTHY", Size: 1, NPop: 3, NPush: 1, Format: FmtNone, Flags: 0},
	OpTailCall:                    {Name: "TAIL_CALL", Size: 3, NPop: 1, NPush: 0, Format: FmtNpop, Flags: OpfJitEligible | OpfJitNeedsArgsBuf | OpfJitNeedsTcoArgs},
	OpTailCallMethod:              {Name: "TAIL_CALL_METHOD", Size: 3, NPop: 2, NPush: 0, Format: FmtNpop, Flags: OpfJitEligible | OpfJitNeedsArgsBuf | OpfJitNeedsTcoArgs},
	OpNew:                         {Name: "NEW", Size: 3, NPop: 2, NPush: 1, Format: FmtNpop, Flags: OpfJitEligible | OpfJitNeedsArgsBuf},
	OpApply:                       {Name: "APPLY", Size: 3, NPop: 3, NPush: 1, Format: FmtU16, Flags: OpfJitEligible | OpfJitNeedsArgsBuf},
	OpSuperApply:                  {Name: "SUPER_APPLY", Size: 3, NPop: 3, NPush: 1, Format: FmtU16, Flags: 0},
	OpNewApply:                    {Name: "NEW_APPLY", Size: 3, NPop: 2, NPush: 1, Format: FmtU16, Flags: OpfJitEligible | OpfJitNeedsArgsBuf},
	OpEval:                        {Name: "EVAL", Size: 5, NPop: 1, NPush: 1, Format: FmtNpop, Flags: 0},
	OpReturn:                      {Name: "RETURN", Size: 1, NPop: 1, NPush: 0, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpReturnUndef:                 {Name: "RETURN_UNDEF", Size: 1, NPop: 0, NPush: 0, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpReturnAsync:                 {Name: "RETURN_ASYNC", Size: 1, NPop: 1, NPush: 0, Format: FmtNone, Flags: 0},
	OpCheckCtor:                   {Name: "CHECK_CTOR", Size: 1, NPop: 0, NPush: 0, Format: FmtNone, Flags: 0},
	OpCheckCtorRet:                {Name: "CHECK_CTOR_RET", Size: 1, NPop: 1, NPush: 2, Format: FmtNone, Flags: 0},
	OpHalt:                        {Name: "HALT", Size: 1, NPop: 0, NPush: 0, Format: FmtNone, Flags: OpfJitEligible},
	OpThrow:                       {Name: "THROW", Size: 1, NPop: 1, NPush: 0, Format: FmtNone, Flags: OpfJitEligible},
	OpThrowError:                  {Name: "THROW_ERROR", Size: 6, NPop: 0, NPush: 0, Format: FmtAtomU8, Flags: OpfJitEligible},
	OpTryPush:                     {Name: "TRY_PUSH", Size: 5, NPop: 0, NPush: 0, Format: FmtLabel, Flags: OpfJitEligible | OpfJitBranch32},
	OpTryPushFinally:              {Name: "TRY_PUSH_FINALLY", Size: 5, NPop: 0, NPush: 0, Format: FmtLabel, Flags: OpfJitBranch32},
	OpTryPop:                      {Name: "TRY_POP", Size: 1, NPop: 0, NPush: 0, Format: FmtNone, Flags: OpfJitEligible},
	OpCatch:                       {Name: "CATCH", Size: 5, NPop: 0, NPush: 1, Format: FmtLabel, Flags: OpfJitEligible | OpfJitBranch32},
	OpFinally:                     {Name: "FINALLY", Size: 5, NPop: 0, NPush: 0, Format: FmtLabel, Flags: OpfJitBranch32},
	OpFinallyRet:                  {Name: "FINALLY_RET", Size: 1, NPop: 1, NPush: 0, Format: FmtNone, Flags: 0},
	OpFinallyDiscard:              {Name: "FINALLY_DISCARD", Size: 1, NPop: 0, NPush: 0, Format: FmtNone, Flags: 0},
	OpUnwindJmp:                   {Name: "UNWIND_JMP", Size: 7, NPop: 0, NPush: 0, Format: FmtLabel, Flags: OpfJitBranch32},
	OpNipCatch:                    {Name: "NIP_CATCH", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpUsingPush:                   {Name: "USING_PUSH", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: 0},
	OpUsingPushAsync:              {Name: "USING_PUSH_ASYNC", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: 0},
	OpDisposeResource:             {Name: "DISPOSE_RESOURCE", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: 0},
	OpDisposeResourceAsync:        {Name: "DISPOSE_RESOURCE_ASYNC", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: 0},
	OpUsingDispose:                {Name: "USING_DISPOSE", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: 0},
	OpUsingDisposeAsync:           {Name: "USING_DISPOSE_ASYNC", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: 0},
	OpUsingDisposeSuppressed:      {Name: "USING_DISPOSE_SUPPRESSED", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: 0},
	OpUsingDisposeAsyncSuppressed: {Name: "USING_DISPOSE_ASYNC_SUPPRESSED", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: 0},
	OpForIn:                       {Name: "FOR_IN", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: 0},
	OpForOf:                       {Name: "FOR_OF", Size: 1, NPop: 1, NPush: 3, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsArgsBuf | OpfJitNeedsIterRoots},
	OpForAwaitOf:                  {Name: "FOR_AWAIT_OF", Size: 1, NPop: 1, NPush: 3, Format: FmtNone, Flags: 0},
	OpIterNext:                    {Name: "ITER_NEXT", Size: 2, NPop: 3, NPush: 5, Format: FmtU8, Flags: 0},
	OpIterGetValue:                {Name: "ITER_GET_VALUE", Size: 1, NPop: 2, NPush: 3, Format: FmtNone, Flags: 0},
	OpIterClose:                   {Name: "ITER_CLOSE", Size: 1, NPop: 3, NPush: 0, Format: FmtNone, Flags: 0},
	OpIterCall:                    {Name: "ITER_CALL", Size: 2, NPop: 4, NPush: 5, Format: FmtU8, Flags: 0},
	OpAwaitIterNext:               {Name: "AWAIT_ITER_NEXT", Size: 1, NPop: 3, NPush: 4, Format: FmtNone, Flags: 0},
	OpDestructureInit:             {Name: "DESTRUCTURE_INIT", Size: 1, NPop: 1, NPush: 3, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsArgsBuf | OpfJitNeedsIterRoots},
	OpDestructureNext:             {Name: "DESTRUCTURE_NEXT", Size: 1, NPop: 3, NPush: 4, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsArgsBuf | OpfJitNeedsIterRoots},
	OpDestructureRest:             {Name: "DESTRUCTURE_REST", Size: 1, NPop: 3, NPush: 4, Format: FmtNone, Flags: 0},
	OpDestructureClose:            {Name: "DESTRUCTURE_CLOSE", Size: 1, NPop: 3, NPush: 0, Format: FmtNone, Flags: OpfJitEligible | OpfJitNeedsArgsBuf | OpfJitNeedsIterRoots},
	OpAwait:                       {Name: "AWAIT", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: 0},
	OpYield:                       {Name: "YIELD", Size: 1, NPop: 1, NPush: 2, Format: FmtNone, Flags: 0},
	OpYieldStarInit:               {Name: "YIELD_STAR_INIT", Size: 3, NPop: 1, NPush: 0, Format: FmtLoc, Flags: 0},
	OpYieldStarNext:               {Name: "YIELD_STAR_NEXT", Size: 3, NPop: 1, NPush: 2, Format: FmtLoc, Flags: 0},
	OpYieldStarThrow:              {Name: "YIELD_STAR_THROW", Size: 3, NPop: 1, NPush: 2, Format: FmtLoc, Flags: 0},
	OpYieldStarReturn:             {Name: "YIELD_STAR_RETURN", Size: 3, NPop: 1, NPush: 2, Format: FmtLoc, Flags: 0},
	OpSpread:                      {Name: "SPREAD", Size: 1, NPop: 1, NPush: 0, Format: FmtNone, Flags: 0},
	OpDefineMethod:                {Name: "DEFINE_METHOD", Size: 6, NPop: 2, NPush: 1, Format: FmtAtomU8, Flags: 0},
	OpDefineMethodComp:            {Name: "DEFINE_METHOD_COMP", Size: 2, NPop: 3, NPush: 1, Format: FmtU8, Flags: OpfJitEligible},
	OpSetName:                     {Name: "SET_NAME", Size: 5, NPop: 1, NPush: 1, Format: FmtAtom, Flags: OpfJitEligible},
	OpSetNameComp:                 {Name: "SET_NAME_COMP", Size: 1, NPop: 2, NPush: 2, Format: FmtNone, Flags: 0},
	OpSetProto:                    {Name: "SET_PROTO", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpSetHomeObj:                  {Name: "SET_HOME_OBJ", Size: 1, NPop: 2, NPush: 2, Format: FmtNone, Flags: 0},
	OpAppend:                      {Name: "APPEND", Size: 1, NPop: 3, NPush: 2, Format: FmtNone, Flags: 0},
	OpCopyDataProps:               {Name: "COPY_DATA_PROPS", Size: 2, NPop: 3, NPush: 3, Format: FmtU8, Flags: 0},
	OpDefineClass:                 {Name: "DEFINE_CLASS", Size: 14, NPop: 2, NPush: 2, Format: FmtAtomU8, Flags: 0},
	OpDefineClassComp:             {Name: "DEFINE_CLASS_COMP", Size: 14, NPop: 3, NPush: 3, Format: FmtAtomU8, Flags: 0},
	OpToObject:                    {Name: "TO_OBJECT", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: 0},
	OpToPropkey:                   {Name: "TO_PROPKEY", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpIsUndef:                     {Name: "IS_UNDEF", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpIsNull:                      {Name: "IS_NULL", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpImport:                      {Name: "IMPORT", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: 0},
	OpImportSource:                {Name: "IMPORT_SOURCE", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: 0},
	OpImportSync:                  {Name: "IMPORT_SYNC", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: 0},
	OpImportDefer:                 {Name: "IMPORT_DEFER", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: 0},
	OpImportDeferDyn:              {Name: "IMPORT_DEFER_DYN", Size: 1, NPop: 2, NPush: 1, Format: FmtNone, Flags: 0},
	OpImportDefault:               {Name: "IMPORT_DEFAULT", Size: 1, NPop: 1, NPush: 1, Format: FmtNone, Flags: OpfJitEligible},
	OpImportNamed:                 {Name: "IMPORT_NAMED", Size: 5, NPop: 1, NPush: 1, Format: FmtAtom, Flags: OpfJitEligible},
	OpExport:                      {Name: "EXPORT", Size: 5, NPop: 1, NPush: 0, Format: FmtAtom, Flags: OpfJitEligible},
	OpExportAll:                   {Name: "EXPORT_ALL", Size: 1, NPop: 1, NPush: 0, Format: FmtNone, Flags: 0},
	OpEnterWith:                   {Name: "ENTER_WITH", Size: 1, NPop: 1, NPush: 0, Format: FmtNone, Flags: 0},
	OpExitWith:                    {Name: "EXIT_WITH", Size: 1, NPop: 0, NPush: 0, Format: FmtNone, Flags: 0},
	OpWithGetVar:                  {Name: "WITH_GET_VAR", Size: 8, NPop: 0, NPush: 1, Format: FmtAtom, Flags: 0},
	OpWithPutVar:                  {Name: "WITH_PUT_VAR", Size: 8, NPop: 1, NPush: 0, Format: FmtAtom, Flags: 0},
	OpWithDelVar:                  {Name: "WITH_DEL_VAR", Size: 5, NPop: 0, NPush: 1, Format: FmtAtom, Flags: 0},
	OpSpecialObj:                  {Name: "SPECIAL_OBJ", Size: 2, NPop: 0, NPush: 1, Format: FmtU8, Flags: OpfJitEligible | OpfJitInlineable},
	OpEmpty:                       {Name: "EMPTY", Size: 1, NPop: 0, NPush: 1, Format: FmtNone, Flags: 0},
	OpDebugger:                    {Name: "DEBUGGER", Size: 1, NPop: 0, NPush: 0, Format: FmtNone, Flags: 0},
	OpNop:                         {Name: "NOP", Size: 1, NPop: 0, NPush: 0, Format: FmtNone, Flags: OpfJitEligible | OpfJitInlineable},
	OpPutConst:                    {Name: "PUT_CONST", Size: 5, NPop: 1, NPush: 0, Format: FmtConst, Flags: 0},
	OpLabel:                       {Name: "LABEL", Size: 5, NPop: 0, NPush: 0, Format: FmtLabel, Flags: OpfJitEligible | OpfJitInlineable},
	OpLineNum:                     {Name: "LINE_NUM", Size: 5, NPop: 0, NPush: 0, Format: FmtU32, Flags: OpfJitEligible | OpfJitInlineable},
	OpColNum:                      {Name: "COL_NUM", Size: 5, NPop: 0, NPush: 0, Format: FmtU32, Flags: OpfJitEligible | OpfJitInlineable},
	OpChkCtor:                     {Name: "CHK_CTOR", Size: 1, NPop: 1, NPush: 0, Format: FmtNone, Flags: 0},
	OpChkProto:                    {Name: "CHK_PROTO", Size: 1, NPop: 1, NPush: 0, Format: FmtNone, Flags: 0},
}

// Name returns the opcode mnemonic.
func (op Opcode) Name() string { return opTable[op].Name }

// Size returns the total instruction length in bytes (opcode + operands).
func (op Opcode) Size() int { return int(opTable[op].Size) }

// Format returns the operand encoding.
func (op Opcode) Format() OpFormat { return opTable[op].Format }

// StackEffect returns (popped, pushed) stack slot counts.
func (op Opcode) StackEffect() (pop, push int) { return int(opTable[op].NPop), int(opTable[op].NPush) }

// Flags returns the opcode's JIT metadata bitset.
func (op Opcode) Flags() uint32 { return opTable[op].Flags }

func (op Opcode) String() string { return opTable[op].Name }
