package engine

// The IANA time zone links, as CLDR records them: each line names every
// identifier one zone answers to, the first being the primary. Two
// identifiers are the same zone exactly when they appear on the same line,
// which is the question ZonedDateTime.equals asks -- Asia/Calcutta and
// Asia/Kolkata are one zone under two names.
//
// Generated from CLDR common/bcp47/timezone.xml.
var cldrTimeZoneAliases = []string{
	"Africa/Asmera Africa/Asmara",
	"Africa/Bamako Africa/Timbuktu",
	"Africa/Cairo Egypt",
	"Africa/Tripoli Libya",
	"America/Adak America/Atka US/Aleutian",
	"America/Anchorage US/Alaska",
	"America/Buenos_Aires America/Argentina/Buenos_Aires",
	"America/Catamarca America/Argentina/Catamarca America/Argentina/ComodRivadavia",
	"America/Chicago US/Central CST6CDT",
	"America/Coral_Harbour America/Atikokan",
	"America/Cordoba America/Argentina/Cordoba America/Rosario",
	"America/Denver America/Shiprock Navajo US/Mountain MST7MDT",
	"America/Detroit US/Michigan",
	"America/Edmonton Canada/Mountain America/Yellowknife",
	"America/Godthab America/Nuuk",
	"America/Halifax Canada/Atlantic",
	"America/Havana Cuba",
	"America/Indiana/Knox America/Knox_IN US/Indiana-Starke",
	"America/Indianapolis America/Fort_Wayne America/Indiana/Indianapolis US/East-Indiana",
	"America/Iqaluit America/Pangnirtung",
	"America/Jamaica Jamaica",
	"America/Jujuy America/Argentina/Jujuy",
	"America/Los_Angeles US/Pacific US/Pacific-New PST8PDT",
	"America/Louisville America/Kentucky/Louisville",
	"America/Manaus Brazil/West",
	"America/Mazatlan Mexico/BajaSur",
	"America/Mendoza America/Argentina/Mendoza",
	"America/Mexico_City Mexico/General",
	"America/New_York US/Eastern EST5EDT",
	"America/Noronha Brazil/DeNoronha",
	"America/Panama EST",
	"America/Phoenix US/Arizona MST",
	"America/Regina Canada/East-Saskatchewan Canada/Saskatchewan",
	"America/Rio_Branco America/Porto_Acre Brazil/Acre",
	"America/Santiago Chile/Continental",
	"America/Sao_Paulo Brazil/East",
	"America/St_Johns Canada/Newfoundland",
	"America/St_Thomas America/Virgin",
	"America/Tijuana America/Ensenada Mexico/BajaNorte America/Santa_Isabel",
	"America/Toronto America/Montreal Canada/Eastern America/Nipigon America/Thunder_Bay",
	"America/Vancouver Canada/Pacific",
	"America/Whitehorse Canada/Yukon",
	"America/Winnipeg Canada/Central America/Rainy_River",
	"Antarctica/McMurdo Antarctica/South_Pole",
	"Arctic/Longyearbyen Atlantic/Jan_Mayen",
	"Asia/Ashgabat Asia/Ashkhabad",
	"Asia/Calcutta Asia/Kolkata",
	"Asia/Dhaka Asia/Dacca",
	"Asia/Hong_Kong Hongkong",
	"Asia/Jerusalem Asia/Tel_Aviv Israel",
	"Asia/Katmandu Asia/Kathmandu",
	"Asia/Macau Asia/Macao",
	"Asia/Makassar Asia/Ujung_Pandang",
	"Asia/Nicosia Europe/Nicosia",
	"Asia/Rangoon Asia/Yangon",
	"Asia/Saigon Asia/Ho_Chi_Minh",
	"Asia/Seoul ROK",
	"Asia/Shanghai Asia/Chongqing Asia/Chungking Asia/Harbin PRC",
	"Asia/Singapore Singapore",
	"Asia/Taipei ROC",
	"Asia/Tehran Iran",
	"Asia/Thimphu Asia/Thimbu",
	"Asia/Tokyo Japan",
	"Asia/Ulaanbaatar Asia/Ulan_Bator Asia/Choibalsan",
	"Asia/Urumqi Asia/Kashgar",
	"Atlantic/Faeroe Atlantic/Faroe",
	"Atlantic/Reykjavik Iceland",
	"Australia/Adelaide Australia/South",
	"Australia/Brisbane Australia/Queensland",
	"Australia/Broken_Hill Australia/Yancowinna",
	"Australia/Darwin Australia/North",
	"Australia/Hobart Australia/Tasmania Australia/Currie",
	"Australia/Lord_Howe Australia/LHI",
	"Australia/Melbourne Australia/Victoria",
	"Australia/Perth Australia/West",
	"Australia/Sydney Australia/ACT Australia/Canberra Australia/NSW",
	"Etc/UTC Etc/UCT Etc/Universal Etc/Zulu UCT UTC Universal Zulu Etc/GMT Etc/GMT+0 Etc/GMT-0 Etc/GMT0 Etc/Greenwich GMT GMT+0 GMT-0 GMT0 Greenwich",
	"Europe/Athens EET",
	"Europe/Brussels CET MET",
	"Europe/Chisinau Europe/Tiraspol",
	"Europe/Dublin Eire",
	"Europe/Istanbul Asia/Istanbul Turkey",
	"Europe/Kiev Europe/Kyiv Europe/Zaporozhye Europe/Uzhgorod",
	"Europe/Lisbon Portugal WET",
	"Europe/London Europe/Belfast GB GB-Eire",
	"Europe/Moscow W-SU",
	"Europe/Warsaw Poland",
	"Pacific/Auckland NZ",
	"Pacific/Chatham NZ-CHAT",
	"Pacific/Easter Chile/EasterIsland",
	"Pacific/Enderbury Pacific/Kanton",
	"Pacific/Honolulu US/Hawaii Pacific/Johnston HST",
	"Pacific/Kwajalein Kwajalein",
	"Pacific/Pago_Pago Pacific/Samoa US/Samoa",
	"Pacific/Ponape Pacific/Pohnpei",
	"Pacific/Truk Pacific/Chuuk Pacific/Yap",
}
