package engine

// The IANA time zone links, as CLDR records them: each line names every
// identifier one zone answers to, the first being the primary. Two identifiers
// are the same zone exactly when they appear on the same line, which is what
// ZonedDateTime.equals asks.
//
// Generated by tools/gencldr from common/bcp47/timezone.xml.
var cldrTimeZoneAliases = []string{}
