package jitmem

import (
	"errors"
	"os"
	"unsafe"
)

func pageSize() int { return os.Getpagesize() }

// ErrSealed is returned by Write on a block that has already been made
// executable. A block is filled once; growing one after the flip would mean
// making it writable again, and a mapping that alternates between writable and
// executable is the thing this package exists to avoid.
var ErrSealed = errors.New("jitmem: block is already executable")

// ErrFull is returned when a write does not fit in the block's mapping.
var ErrFull = errors.New("jitmem: block is full")

// Block is a page-aligned region that holds generated code.
//
// The zero value is not usable; obtain one from Alloc. A Block is not safe for
// concurrent writes, which costs nothing: code is generated by one goroutine and
// only becomes reachable by others once Protect has returned.
type Block struct {
	mem    []byte // the whole mapping, always page-aligned and page-multiple
	n      int    // bytes written so far
	sealed bool   // Protect has run; mem is read+execute
}

// Alloc reserves at least size bytes of writable, non-executable memory,
// rounded up to a whole number of pages.
func Alloc(size int) (*Block, error) {
	if size <= 0 {
		return nil, errors.New("jitmem: size must be positive")
	}
	ps := pageSize()
	rounded := (size + ps - 1) &^ (ps - 1)
	mem, err := allocRW(rounded)
	if err != nil {
		return nil, err
	}
	return &Block{mem: mem}, nil
}

// Write appends code to the block. It reports ErrFull rather than growing:
// a block's address is baked into the code that jumps within it, so a mapping
// that moved would invalidate every relative offset already emitted.
func (b *Block) Write(code []byte) (int, error) {
	if b.sealed {
		return 0, ErrSealed
	}
	if b.n+len(code) > len(b.mem) {
		return 0, ErrFull
	}
	copy(b.mem[b.n:], code)
	off := b.n
	b.n += len(code)
	return off, nil
}

// Protect flips the block to read-execute and makes the writes visible to the
// instruction fetcher.
//
// The cache flush is not optional on arm64, where the data and instruction
// caches are not coherent: the bytes Write stored may still be sitting in the
// D-cache when the core tries to fetch them. It is a no-op on amd64, which
// snoops.
func (b *Block) Protect() error {
	if b.sealed {
		return nil
	}
	if err := protectRX(b.mem); err != nil {
		return err
	}
	flushICache(b.mem)
	b.sealed = true
	return nil
}

// Addr is the address of the block's first byte, which is where a caller enters
// code written at offset zero.
func (b *Block) Addr() uintptr {
	if len(b.mem) == 0 {
		return 0
	}
	return uintptr(unsafe.Pointer(&b.mem[0]))
}

// AddrAt is the address of a particular offset, as returned by Write.
func (b *Block) AddrAt(off int) uintptr { return b.Addr() + uintptr(off) }

// Len is the number of bytes written.
func (b *Block) Len() int { return b.n }

// Cap is the size of the mapping, which is the block's rounded-up size.
func (b *Block) Cap() int { return len(b.mem) }

// Executable reports whether Protect has run.
func (b *Block) Executable() bool { return b.sealed }

// Free releases the mapping. Using the block, or any address derived from it,
// after Free is a use-after-free of executable memory; callers keep a block
// alive for as long as any compiled function in it can still be entered.
func (b *Block) Free() error {
	if b.mem == nil {
		return nil
	}
	err := release(b.mem)
	b.mem, b.n, b.sealed = nil, 0, false
	return err
}
