// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: Proxy, internal 'get' calls
// subtest: RegExp.prototype.flags
var __ok = (function () {// RegExp.prototype.flags -> Get -> [[Get]]
var expected = [];
// Sorted alphabetically by shortname – "gimsuy".
if ('hasIndices' in RegExp.prototype) expected.push('hasIndices');
if ('global' in RegExp.prototype) expected.push('global');
if ('ignoreCase' in RegExp.prototype) expected.push('ignoreCase');
if ('multiline' in RegExp.prototype) expected.push('multiline');
if ('dotAll' in RegExp.prototype) expected.push('dotAll');
if ('unicode' in RegExp.prototype) expected.push('unicode');
if ('unicodeSets' in RegExp.prototype) expected.push('unicodeSets');
if ('sticky' in RegExp.prototype) expected.push('sticky');

var actual = [];
var p = new Proxy({}, { get: function (o, k) { actual.push(k); return o[k]; }});
Object.getOwnPropertyDescriptor(RegExp.prototype, 'flags').get.call(p);
if (expected.length !== actual.length) return false;
for (var i = 0; i < expected.length; i++) {
  if (expected[i] !== actual[i]) return false;
}
return true;
})();
if (!__ok) { throw new Error("compat-table check failed: " + __ok); }
