// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: own property order
// subtest: Object.keys
var __ok = (function () {var obj = {
  // Non-negative integer names appear first in value order
  2: true,
  0: true,
  1: true,
  // Other string names appear in source order
  ' ': true,
  // Non-negative integers are sorted above other names
  9: true,
  D: true,
  B: true,
  // Negative integers are treated as other names
  '-1': true
};
// Other string names are added in order of creation
obj.A = true;
// Non-negative integer names, conversely, ignore order of creation
obj[3] = true;
// Having a total of 20+ properties doesn't affect property order
"EFGHIJKLMNOPQRSTUVWXYZ".split('').forEach(function (key){
  obj[key] = true;
});
// Object.defineProperty doesn't affect the above rules
Object.defineProperty(obj, 'C', { value: true, enumerable: true });
Object.defineProperty(obj, '4', { value: true, enumerable: true });
// Deleting and reinserting a property doesn't preserve its position
delete obj[2];
obj[2] = true;

var forInOrder = '';
for(var key in obj)forInOrder += key;

return Object.keys(obj).join('') === forInOrder;
})();
if (!__ok) { throw new Error("compat-table check failed: " + __ok); }
