// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: own property order
// subtest: Object.assign
var __ok = (function () {var result = '';
var target = {};

"012349 DBACEFGHIJKLMNOPQRST".split('').concat(-1).forEach(function (key){
  Object.defineProperty(target, key, {
    set: function (){
      result += key;
    }
  })
});

var obj = {2: 2, 0: 0, 1: 1, ' ': ' ', 9: 9, D: 'D', B: 'B', '-1': '-1'};
Object.defineProperty(obj, 'A', {value: 'A',  enumerable: true});
Object.defineProperty(obj, '3', {value: '3',  enumerable: true});
Object.defineProperty(obj, 'C', {value: 'C',  enumerable: true});
Object.defineProperty(obj, '4', {value: '4',  enumerable: true});
delete obj[2];
obj[2] = true;

"EFGHIJKLMNOPQRST".split('').forEach(function (key){
  obj[key] = key;
});

Object.assign(target, obj);

return result === "012349 DB-1ACEFGHIJKLMNOPQRST";
})();
if (!__ok) { throw new Error("compat-table check failed: " + __ok); }
