// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: proper tail calls (tail call optimisation)
// subtest: mutual recursion
var __ok = (function () {"use strict";
function f(n){
  if (n <= 0) {
    return  "foo";
  }
  return g(n - 1);
}
function g(n){
  if (n <= 0) {
    return  "bar";
  }
  return f(n - 1);
}
return f(1e6) === "foo" && f(1e6+1) === "bar";
})();
if (!__ok) { throw new Error("compat-table check failed: " + __ok); }
