// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: typed arrays
// subtest: %TypedArray%.prototype.values
var __ok = (function () {return typeof Int8Array.prototype.values === "function" &&
    typeof Uint8Array.prototype.values === "function" &&
    typeof Uint8ClampedArray.prototype.values === "function" &&
    typeof Int16Array.prototype.values === "function" &&
    typeof Uint16Array.prototype.values === "function" &&
    typeof Int32Array.prototype.values === "function" &&
    typeof Uint32Array.prototype.values === "function" &&
    typeof Float32Array.prototype.values === "function" &&
    typeof Float64Array.prototype.values === "function";
})();
if (!__ok) { throw new Error("compat-table check failed: " + __ok); }
