// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: well-known symbols
// subtest: Symbol.species, Promise.prototype.then
var __ok = (function () {var promise      = new Promise(function (resolve){ resolve(42); });
var FakePromise1 = promise.constructor = function (exec){ exec(function (){}, function (){}); };
var FakePromise2 = function (exec){ exec(function (){}, function (){}); };
Object.defineProperty(FakePromise1, Symbol.species, {value: FakePromise2});
return promise.then(function (){}) instanceof FakePromise2;
})();
if (!__ok) { throw new Error("compat-table check failed: " + __ok); }
