// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: .at() method on the built-in indexables
// subtest: String.prototype.at()
var __ok = (function () {var str = 'abc';
return str.at(0) === 'a'
  && str.at(-3) === 'a'
  && str.at(1) === 'b'
  && str.at(-2) === 'b'
  && str.at(2) === 'c'
  && str.at(-1) === 'c'
  && str.at(3) === undefined
  && str.at(-4) === undefined;
})();
if (!__ok) { throw new Error("compat-table check failed: " + __ok); }
