// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: Object static methods
// subtest: Object.values
var __ok = (function () {
          var obj = Object.create({ a: "qux", d: "qux" });
          obj.a = "foo";
          obj.b = "bar";
          obj.c = "baz";
          var v = Object.values(obj);
          return Array.isArray(v) && String(v) === "foo,bar,baz";
        
})();
if (__ok !== true) { throw new Error("compat-table check failed: " + __ok); }
