// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: Array Grouping
// subtest: Object.groupBy()
var __ok = (function () {const array = [1, 2, 3, 4];
const obj = Object.groupBy(array, (num, index) => {
  return num % 2 === 0 ? 'even': 'odd';
});
return !('toString' in obj) && obj.even[0] == 2 && obj.odd[0] == 1;
})();
if (!__ok) { throw new Error("compat-table check failed: " + __ok); }
