// Code generated by tools/compatgen from kangax/compat-table; DO NOT EDIT.
// SPDX-License-Identifier: MIT  (https://github.com/kangax/compat-table)
var global = this;
if (typeof globalThis !== "undefined") { global = globalThis; }
global.global = global;
global.__createIterableObject = function (arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== "function" || !Symbol.iterator) { return {}; }
  arr.length++;
  var iterator = {
    next: function () { return { value: arr.shift(), done: arr.length <= 0 }; },
    "return": methods["return"],
    "throw": methods["throw"]
  };
  var iterable = {};
  iterable[Symbol.iterator] = function () { return iterator; };
  return iterable;
};
// pin: 1bcd416b9f4399c71d3234c06bd0441074195743
// feature: Promise.prototype.finally
// subtest: basic support
globalThis.__asyncTestPending = true;
global.asyncTestPassed = function () { globalThis.__asyncTestPending = false; };
(function () {var p1 = Promise.resolve("foo");
var p2 = Promise.reject("bar");
var score = 0;
function thenFn(result) {
  score += (result === "foo");
  check();
}
function catchFn(result) {
  score += (result === "bar");
  check();
}
function finallyFn() {
  score += (arguments.length === 0);
  check();
}
p1.then(thenFn);
p1.finally(finallyFn);
p1.finally(function () {
  // should return a new Promise
  score += p1.finally() !== p1;
  check();
});
p2.catch (catchFn);
p2.finally(finallyFn);
function check() {
  if (score === 5) asyncTestPassed();
}
})();
