// Command genops parses ant's include/silver/opcode.h and generates
// internal/engine/opcode.go: opcode constants (in definition order),
// instruction sizes, stack effects, operand formats, and per-opcode JIT flags.
//
// Usage:
//
//	go run ./tools/genops -in <ant>/include/silver/opcode.h -out internal/engine/opcode.go
//
// The generated file is committed; regenerate only when opcode.h changes.
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strconv"
	"strings"
)

var (
	fmtRe  = regexp.MustCompile(`^\s*OP_FMT\(\s*(\w+)\s*\)`)
	defRe  = regexp.MustCompile(`^\s*(?:OP_DEF|op_def)\(\s*(\w+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\w+)\s*\)`)
	flagRe = regexp.MustCompile(`^\s*OP_FLAG\(\s*(\w+)\s*,\s*([^)]+)\)`)
)

type opdef struct {
	name              string
	size, npop, npush int
	format            string
	flags             string
}

func main() {
	in := flag.String("in", "", "path to ant include/silver/opcode.h")
	out := flag.String("out", "", "path to generated opcode.go")
	flag.Parse()
	if *in == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "genops: -in and -out required")
		os.Exit(2)
	}

	src, err := os.ReadFile(*in)
	if err != nil {
		fatal(err)
	}

	var formats []string
	var ops []opdef
	flags := map[string]string{}

	sc := bufio.NewScanner(bytes.NewReader(src))
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line := sc.Text()
		if m := fmtRe.FindStringSubmatch(line); m != nil {
			formats = append(formats, m[1])
			continue
		}
		if m := defRe.FindStringSubmatch(line); m != nil {
			ops = append(ops, opdef{
				name:   m[1],
				size:   atoi(m[2]),
				npop:   atoi(m[3]),
				npush:  atoi(m[4]),
				format: m[5],
			})
			continue
		}
		if m := flagRe.FindStringSubmatch(line); m != nil {
			flags[m[1]] = strings.TrimSpace(m[2])
		}
	}
	if err := sc.Err(); err != nil {
		fatal(err)
	}
	for i := range ops {
		ops[i].flags = flags[ops[i].name]
	}

	code := generate(formats, ops)
	formatted, err := format.Source(code)
	if err != nil {
		// Emit unformatted for debugging, then fail.
		os.WriteFile(*out, code, 0o644)
		fatal(fmt.Errorf("gofmt: %w", err))
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fatal(err)
	}
	fmt.Fprintf(os.Stderr, "genops: wrote %d opcodes, %d formats to %s\n", len(ops), len(formats), *out)
}

// collect the set of JIT flag identifiers referenced, so we can define them.
func collectFlags(ops []opdef) []string {
	seen := map[string]bool{}
	var order []string
	for _, op := range ops {
		for f := range strings.SplitSeq(op.flags, "|") {
			f = strings.TrimSpace(f)
			if f == "" || seen[f] {
				continue
			}
			seen[f] = true
			order = append(order, f)
		}
	}
	return order
}

func generate(formats []string, ops []opdef) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by tools/genops from ant include/silver/opcode.h. DO NOT EDIT.\n\n")
	b.WriteString("package engine\n\n")

	// Operand formats.
	b.WriteString("// OpFormat classifies an opcode's inline operand encoding (ant OP_FMT).\n")
	b.WriteString("type OpFormat uint8\n\nconst (\n")
	for i, f := range formats {
		if i == 0 {
			fmt.Fprintf(&b, "\tFmt%s OpFormat = iota\n", camel(f))
		} else {
			fmt.Fprintf(&b, "\tFmt%s\n", camel(f))
		}
	}
	b.WriteString(")\n\n")

	b.WriteString("var opFormatNames = [...]string{\n")
	for _, f := range formats {
		fmt.Fprintf(&b, "\tFmt%s: %q,\n", camel(f), f)
	}
	b.WriteString("}\n\n")
	b.WriteString("func (f OpFormat) String() string { return opFormatNames[f] }\n\n")

	// Opcode constants.
	b.WriteString("// Opcode is a Silver bytecode operation (ant OP_DEF).\n")
	b.WriteString("type Opcode uint8\n\nconst (\n")
	for i, op := range ops {
		if i == 0 {
			fmt.Fprintf(&b, "\tOp%s Opcode = iota\n", camel(op.name))
		} else {
			fmt.Fprintf(&b, "\tOp%s\n", camel(op.name))
		}
	}
	fmt.Fprintf(&b, "\n\tNumOpcodes = %d\n", len(ops))
	b.WriteString(")\n\n")

	// JIT flag identifiers.
	jitFlags := collectFlags(ops)
	if len(jitFlags) > 0 {
		b.WriteString("// Per-opcode JIT metadata flags (ant OP_FLAG / SV_OPF_*).\n")
		b.WriteString("const (\n")
		for i, f := range jitFlags {
			goName := jitFlagGoName(f)
			if i == 0 {
				fmt.Fprintf(&b, "\t%s uint32 = 1 << iota\n", goName)
			} else {
				fmt.Fprintf(&b, "\t%s\n", goName)
			}
		}
		b.WriteString(")\n\n")
	}

	// Per-opcode metadata table.
	b.WriteString("type opInfo struct {\n")
	b.WriteString("\tName   string\n")
	b.WriteString("\tSize   uint8\n")
	b.WriteString("\tNPop   uint8\n")
	b.WriteString("\tNPush  uint8\n")
	b.WriteString("\tFormat OpFormat\n")
	b.WriteString("\tFlags  uint32\n")
	b.WriteString("}\n\n")

	b.WriteString("var opTable = [NumOpcodes]opInfo{\n")
	for _, op := range ops {
		flagExpr := "0"
		if op.flags != "" {
			parts := strings.Split(op.flags, "|")
			var gos []string
			for _, p := range parts {
				p = strings.TrimSpace(p)
				if p == "" {
					continue
				}
				gos = append(gos, jitFlagGoName(p))
			}
			if len(gos) > 0 {
				flagExpr = strings.Join(gos, " | ")
			}
		}
		fmt.Fprintf(&b, "\tOp%s: {Name: %q, Size: %d, NPop: %d, NPush: %d, Format: Fmt%s, Flags: %s},\n",
			camel(op.name), op.name, op.size, op.npop, op.npush, camel(op.format), flagExpr)
	}
	b.WriteString("}\n\n")

	// Accessors.
	b.WriteString("// Name returns the opcode mnemonic.\n")
	b.WriteString("func (op Opcode) Name() string { return opTable[op].Name }\n\n")
	b.WriteString("// Size returns the total instruction length in bytes (opcode + operands).\n")
	b.WriteString("func (op Opcode) Size() int { return int(opTable[op].Size) }\n\n")
	b.WriteString("// Format returns the operand encoding.\n")
	b.WriteString("func (op Opcode) Format() OpFormat { return opTable[op].Format }\n\n")
	b.WriteString("// StackEffect returns (popped, pushed) stack slot counts.\n")
	b.WriteString("func (op Opcode) StackEffect() (pop, push int) { return int(opTable[op].NPop), int(opTable[op].NPush) }\n\n")
	b.WriteString("// Flags returns the opcode's JIT metadata bitset.\n")
	b.WriteString("func (op Opcode) Flags() uint32 { return opTable[op].Flags }\n\n")
	b.WriteString("func (op Opcode) String() string { return opTable[op].Name }\n")

	return b.Bytes()
}

// jitFlagGoName maps SV_OPF_JIT_FOO -> OpfJitFoo for a Go-idiomatic constant.
func jitFlagGoName(c string) string {
	c = strings.TrimPrefix(c, "SV_")
	return camel(strings.ToLower(c))
}

// camel converts snake_case / SCREAMING to UpperCamelCase.
func camel(s string) string {
	parts := strings.Split(strings.ToLower(s), "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}

func atoi(s string) int {
	n, err := strconv.Atoi(s)
	if err != nil {
		fatal(err)
	}
	return n
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "genops:", err)
	os.Exit(1)
}
